/** Slug → curated Wash `/icons/brands` component name. */
export const WASH_BRAND_BY_SLUG: Record<string, string> = {
  angular: 'Angular',
  astro: 'Astro',
  daisyui: 'Daisyui',
  discord: 'Discord',
  eleventy: 'Eleventy',
  github: 'GitHub',
  google: 'Google',
  html5: 'Html5',
  lit: 'Lit',
  lucide: 'Lucide',
  nextdotjs: 'Nextjs',
  npm: 'Npm',
  nuxt: 'Nuxt',
  preact: 'Preact',
  qwik: 'Qwik',
  react: 'ReactBrand',
  remix: 'Remix',
  simpleicons: 'SimpleIcons',
  solid: 'Solid',
  svelte: 'Svelte',
  tailwindcss: 'Tailwindcss',
  typescript: 'TypeScript',
  vite: 'Vite',
  vuedotjs: 'Vue',
  x: 'X',
}
