/* Auto-generated by scripts/embed-snapshot.mjs. Do not edit. */
export type EmbeddedComposable = {
  name: string
  packagePath: string
  relativeFile: string
  params: string[]
  kdoc?: string
  excerpt: string
}

export type EmbeddedComposeSnapshot = {
  generatedAt: string
  pigments: string[]
  lucide: string[]
  brands: string[]
  primitives: string[]
  components: string[]
  composables: Record<string, EmbeddedComposable>
}

export const embeddedSnapshot: EmbeddedComposeSnapshot = {
  "generatedAt": "2026-09-05T13:11:25.890Z",
  "pigments": [
    "mineral",
    "indigo",
    "celadon",
    "vermilion",
    "sepia",
    "cobalt",
    "moss",
    "saffron",
    "slate",
    "lake",
    "ultramarine",
    "viridian",
    "madder",
    "ochre",
    "umber",
    "ivory",
    "cerulean",
    "crimson",
    "olive",
    "sienna",
    "turquoise",
    "lavender",
    "charcoal",
    "coral",
    "pine",
    "bronze",
    "mist",
    "rust",
    "jade",
    "ink"
  ],
  "lucide": [
    "AlignLeft",
    "Aperture",
    "AppWindow",
    "ArrowLeftRight",
    "ArrowRight",
    "ArrowRightLeft",
    "BadgeCheck",
    "Bell",
    "BookOpen",
    "Box",
    "Calendar",
    "CalendarClock",
    "ChartBar",
    "ChartCandlestick",
    "ChartGantt",
    "ChartLine",
    "ChartNoAxesColumn",
    "ChartPie",
    "ChartScatter",
    "Check",
    "ChevronDown",
    "ChevronRight",
    "ChevronUp",
    "ChevronsDownUp",
    "ChevronsLeftRight",
    "Circle",
    "CircleDot",
    "CircleFadingPlus",
    "CircleGauge",
    "Columns2",
    "Combine",
    "Droplets",
    "EllipsisVertical",
    "ExternalLink",
    "Eye",
    "EyeOff",
    "FileUp",
    "FoldVertical",
    "FolderOpen",
    "GalleryHorizontal",
    "GalleryHorizontalEnd",
    "GalleryVertical",
    "Gauge",
    "Grid2x2",
    "Group",
    "Hash",
    "Heart",
    "History",
    "Image",
    "Images",
    "KeyRound",
    "Keyboard",
    "Layers",
    "LayoutDashboard",
    "LayoutGrid",
    "Link",
    "List",
    "ListChecks",
    "ListFilter",
    "ListOrdered",
    "LoaderCircle",
    "Mail",
    "Menu",
    "MessageCircle",
    "MessageSquare",
    "MessageSquareMore",
    "MessagesSquare",
    "MonitorSmartphone",
    "MousePointerClick",
    "Network",
    "Palette",
    "PanelBottom",
    "PanelBottomClose",
    "PanelLeft",
    "PanelTop",
    "PanelTopDashed",
    "PanelTopOpen",
    "PictureInPicture2",
    "Plus",
    "QrCode",
    "Radar",
    "Radio",
    "RectangleHorizontal",
    "RotateCw",
    "ScrollText",
    "Search",
    "SeparatorHorizontal",
    "Settings",
    "Settings2",
    "Shapes",
    "Share2",
    "Sheet",
    "ShieldCheck",
    "ShoppingBag",
    "SlidersHorizontal",
    "Sparkles",
    "Square",
    "SquareChevronDown",
    "SquareDashed",
    "SquareMenu",
    "SquareMousePointer",
    "SquareStack",
    "Star",
    "Sun",
    "SunMoon",
    "SwatchBook",
    "Table2",
    "Tag",
    "Tags",
    "TextCursorInput",
    "TextSearch",
    "Timer",
    "ToggleLeft",
    "TrendingUp",
    "TriangleAlert",
    "UserRound",
    "Waves",
    "X"
  ],
  "brands": [
    "Angular",
    "Astro",
    "Daisyui",
    "Eleventy",
    "GitHub",
    "Html5",
    "Lit",
    "Lucide",
    "Nextjs",
    "Nuxt",
    "Preact",
    "Qwik",
    "ReactBrand",
    "Remix",
    "SimpleIcons",
    "Solid",
    "Svelte",
    "Tailwindcss",
    "TypeScript",
    "Vite",
    "Vue"
  ],
  "primitives": [
    "WashBottomSheet",
    "WashButton",
    "WashCheckbox",
    "WashChip",
    "WashDialog",
    "WashDivider",
    "WashDrawer",
    "WashDropdownMenu",
    "WashFormField",
    "WashIconButton",
    "WashInput",
    "WashLoading",
    "WashPanel",
    "WashRadio",
    "WashScaffold",
    "WashSelect",
    "WashSlider",
    "WashText",
    "WashTextarea",
    "WashToast",
    "WashToggle",
    "WashTooltip",
    "WashTopBar"
  ],
  "components": [
    "StudioLoading",
    "WashAccordion",
    "WashBackground",
    "WashCard",
    "WashTabs",
    "WashThemeSwitcher"
  ],
  "composables": {
    "WashBottomSheet": {
      "name": "WashBottomSheet",
      "packagePath": "com.mariesta.menzies.washui.primitives",
      "relativeFile": "primitives/WashBottomSheet.kt",
      "params": [
        "open: Boolean",
        "onDismiss: () -> Unit",
        "modifier: Modifier = Modifier",
        "content: @Composable ColumnScope.() -> Unit"
      ],
      "kdoc": "Compact bottom-anchored sheet using a dialog host (no Material ModalBottomSheet).\nGood enough for gallery demos of sheet-style filters.",
      "excerpt": "@Composable\nfun WashBottomSheet(\n    open: Boolean,\n    onDismiss: () -> Unit,\n    modifier: Modifier = Modifier,\n    content: @Composable ColumnScope.() -> Unit,\n) {\n  …\n}"
    },
    "WashButton": {
      "name": "WashButton",
      "packagePath": "com.mariesta.menzies.washui.primitives",
      "relativeFile": "primitives/WashButton.kt",
      "params": [
        "onClick: () -> Unit",
        "modifier: Modifier = Modifier",
        "variant: WashButtonVariant = WashButtonVariant.Default",
        "size: WashButtonSize = WashButtonSize.Md",
        "enabled: Boolean = true",
        "loading: Boolean = false",
        "ripple: Boolean = true",
        "content: @Composable () -> Unit"
      ],
      "excerpt": "@Composable\nfun WashButton(\n    onClick: () -> Unit,\n    modifier: Modifier = Modifier,\n    variant: WashButtonVariant = WashButtonVariant.Default,\n    size: WashButtonSize = WashButtonSize.Md,\n    enabled: Boolean = true,\n    loading: Boolean = false,\n    ripple: Boolean = true,\n    content: @Composable () -> Unit,\n) {\n  …\n}"
    },
    "WashCheckbox": {
      "name": "WashCheckbox",
      "packagePath": "com.mariesta.menzies.washui.primitives",
      "relativeFile": "primitives/WashCheckbox.kt",
      "params": [
        "checked: Boolean",
        "onCheckedChange: (Boolean) -> Unit",
        "modifier: Modifier = Modifier",
        "label: String? = null",
        "enabled: Boolean = true"
      ],
      "excerpt": "@Composable\nfun WashCheckbox(\n    checked: Boolean,\n    onCheckedChange: (Boolean) -> Unit,\n    modifier: Modifier = Modifier,\n    label: String? = null,\n    enabled: Boolean = true,\n) {\n  …\n}"
    },
    "WashChip": {
      "name": "WashChip",
      "packagePath": "com.mariesta.menzies.washui.primitives",
      "relativeFile": "primitives/WashChip.kt",
      "params": [
        "selected: Boolean",
        "onClick: () -> Unit",
        "label: String",
        "modifier: Modifier = Modifier",
        "enabled: Boolean = true"
      ],
      "kdoc": "Compact selectable chip (Foundation). Replaces Material FilterChip hosts.",
      "excerpt": "@Composable\nfun WashChip(\n    selected: Boolean,\n    onClick: () -> Unit,\n    label: String,\n    modifier: Modifier = Modifier,\n    enabled: Boolean = true,\n) {\n  …\n}"
    },
    "WashDialog": {
      "name": "WashDialog",
      "packagePath": "com.mariesta.menzies.washui.primitives",
      "relativeFile": "primitives/WashDialog.kt",
      "params": [
        "open: Boolean",
        "onClose: () -> Unit",
        "title: String",
        "modifier: Modifier = Modifier",
        "description: String? = null",
        "tone: WashDialogTone = WashDialogTone.Primary",
        "dismissOnClickOutside: Boolean = true",
        "actions: @Composable (() -> Unit)? = null",
        "content: @Composable (() -> Unit)? = null"
      ],
      "excerpt": "@Composable\nfun WashDialog(\n    open: Boolean,\n    onClose: () -> Unit,\n    title: String,\n    modifier: Modifier = Modifier,\n    description: String? = null,\n    tone: WashDialogTone = WashDialogTone.Primary,\n    dismissOnClickOutside: Boolean = true,\n    actions: @Composable (() -> Unit)? = null,\n    content: @Composable (() -> Unit)? = null,\n) {\n  …\n}"
    },
    "WashDivider": {
      "name": "WashDivider",
      "packagePath": "com.mariesta.menzies.washui.primitives",
      "relativeFile": "primitives/WashDivider.kt",
      "params": [
        "modifier: Modifier = Modifier",
        "color: Color = Color.Unspecified",
        "thickness: Dp = 1.dp"
      ],
      "excerpt": "@Composable\nfun WashDivider(\n    modifier: Modifier = Modifier,\n    color: Color = Color.Unspecified,\n    thickness: Dp = 1.dp,\n) {\n  …\n}"
    },
    "WashModalDrawer": {
      "name": "WashModalDrawer",
      "packagePath": "com.mariesta.menzies.washui.primitives",
      "relativeFile": "primitives/WashDrawer.kt",
      "params": [
        "open: Boolean",
        "onDismiss: () -> Unit",
        "modifier: Modifier = Modifier",
        "drawerWidth: Dp = 280.dp",
        "scrimColor: Color = Color.Black.copy(alpha = 0.4f)",
        "drawerContent: @Composable ColumnScope.() -> Unit",
        "content: @Composable BoxScope.() -> Unit"
      ],
      "kdoc": "Modal side drawer with scrim. Wash-owned chrome; no Material NavigationDrawer.\nDrawer panel pads [WindowInsets.safeDrawing] on start/top/bottom so header\ncontent clears status bar and cutouts when drawn edge-to-edge (sibling of\n[WashScaffold], so it is not already consumed).",
      "excerpt": "@Composable\nfun WashModalDrawer(\n    open: Boolean,\n    onDismiss: () -> Unit,\n    modifier: Modifier = Modifier,\n    drawerWidth: Dp = 280.dp,\n    scrimColor: Color = Color.Black.copy(alpha = 0.4f),\n    drawerContent: @Composable ColumnScope.() -> Unit,\n    content: @Composable BoxScope.() -> Unit,\n) {\n  …\n}"
    },
    "WashDrawer": {
      "name": "WashModalDrawer",
      "packagePath": "com.mariesta.menzies.washui.primitives",
      "relativeFile": "primitives/WashDrawer.kt",
      "params": [
        "open: Boolean",
        "onDismiss: () -> Unit",
        "modifier: Modifier = Modifier",
        "drawerWidth: Dp = 280.dp",
        "scrimColor: Color = Color.Black.copy(alpha = 0.4f)",
        "drawerContent: @Composable ColumnScope.() -> Unit",
        "content: @Composable BoxScope.() -> Unit"
      ],
      "kdoc": "Modal side drawer with scrim. Wash-owned chrome; no Material NavigationDrawer.\nDrawer panel pads [WindowInsets.safeDrawing] on start/top/bottom so header\ncontent clears status bar and cutouts when drawn edge-to-edge (sibling of\n[WashScaffold], so it is not already consumed).",
      "excerpt": "@Composable\nfun WashModalDrawer(\n    open: Boolean,\n    onDismiss: () -> Unit,\n    modifier: Modifier = Modifier,\n    drawerWidth: Dp = 280.dp,\n    scrimColor: Color = Color.Black.copy(alpha = 0.4f),\n    drawerContent: @Composable ColumnScope.() -> Unit,\n    content: @Composable BoxScope.() -> Unit,\n) {\n  …\n}"
    },
    "WashDropdownMenu": {
      "name": "WashDropdownMenu",
      "packagePath": "com.mariesta.menzies.washui.primitives",
      "relativeFile": "primitives/WashDropdownMenu.kt",
      "params": [
        "open: Boolean",
        "onDismiss: () -> Unit",
        "modifier: Modifier = Modifier",
        "items: List<String>",
        "onItemClick: (String) -> Unit = {}"
      ],
      "kdoc": "Anchored action menu. Mirrors web recipe `menu rounded-box border border-ink-border bg-base-100`.",
      "excerpt": "@Composable\nfun WashDropdownMenu(\n    open: Boolean,\n    onDismiss: () -> Unit,\n    modifier: Modifier = Modifier,\n    items: List<String>,\n    onItemClick: (String) -> Unit = {},\n) {\n  …\n}"
    },
    "WashFormField": {
      "name": "WashFormField",
      "packagePath": "com.mariesta.menzies.washui.primitives",
      "relativeFile": "primitives/WashFormField.kt",
      "params": [
        "label: String?",
        "hint: String?",
        "error: String?",
        "requiredMark: Boolean",
        "modifier: Modifier = Modifier",
        "content: @Composable () -> Unit"
      ],
      "excerpt": "fun WashFormField(\n    label: String?,\n    hint: String?,\n    error: String?,\n    requiredMark: Boolean,\n    modifier: Modifier = Modifier,\n    content: @Composable () -> Unit,\n) {\n  …\n}"
    },
    "WashIconButton": {
      "name": "WashIconButton",
      "packagePath": "com.mariesta.menzies.washui.primitives",
      "relativeFile": "primitives/WashIconButton.kt",
      "params": [
        "onClick: () -> Unit",
        "imageVector: ImageVector",
        "contentDescription: String",
        "modifier: Modifier = Modifier",
        "enabled: Boolean = true",
        "tint: Color = Color.Unspecified",
        "iconSize: Dp = 22.dp",
        "buttonSize: Dp = 40.dp"
      ],
      "kdoc": "Icon-only control with Wash ripple. Matches ghost square btn patterns from the web recipes.",
      "excerpt": "@Composable\nfun WashIconButton(\n    onClick: () -> Unit,\n    imageVector: ImageVector,\n    contentDescription: String,\n    modifier: Modifier = Modifier,\n    enabled: Boolean = true,\n    tint: Color = Color.Unspecified,\n    iconSize: Dp = 22.dp,\n    buttonSize: Dp = 40.dp,\n) {\n  …\n}"
    },
    "WashInput": {
      "name": "WashInput",
      "packagePath": "com.mariesta.menzies.washui.primitives",
      "relativeFile": "primitives/WashInput.kt",
      "params": [
        "value: String",
        "onValueChange: (String) -> Unit",
        "modifier: Modifier = Modifier",
        "label: String? = null",
        "hint: String? = null",
        "error: String? = null",
        "requiredMark: Boolean = false",
        "enabled: Boolean = true",
        "singleLine: Boolean = true",
        "keyboardOptions: KeyboardOptions = KeyboardOptions.Default",
        "visualTransformation: VisualTransformation = VisualTransformation.None",
        "placeholder: String? = null"
      ],
      "excerpt": "@Composable\nfun WashInput(\n    value: String,\n    onValueChange: (String) -> Unit,\n    modifier: Modifier = Modifier,\n    label: String? = null,\n    hint: String? = null,\n    error: String? = null,\n    requiredMark: Boolean = false,\n    enabled: Boolean = true,\n    singleLine: Boolean = true,\n    keyboardOptions: KeyboardOptions = KeyboardOptions.Default,\n    visualTransformation: VisualTransformation = VisualTransformation.None,\n    placeholder: String? = null,\n) {\n  …\n}"
    },
    "WashLoading": {
      "name": "WashLoading",
      "packagePath": "com.mariesta.menzies.washui.primitives",
      "relativeFile": "primitives/WashLoading.kt",
      "params": [
        "modifier: Modifier = Modifier",
        "label: String = \"Loading\"",
        "size: WashLoadingSize = WashLoadingSize.Md",
        "variant: WashLoadingVariant = WashLoadingVariant.Spinner"
      ],
      "excerpt": "@Composable\nfun WashLoading(\n    modifier: Modifier = Modifier,\n    label: String = \"Loading\",\n    size: WashLoadingSize = WashLoadingSize.Md,\n    variant: WashLoadingVariant = WashLoadingVariant.Spinner,\n) {\n  …\n}"
    },
    "WashPanel": {
      "name": "WashPanel",
      "packagePath": "com.mariesta.menzies.washui.primitives",
      "relativeFile": "primitives/WashPanel.kt",
      "params": [
        "modifier: Modifier = Modifier",
        "flush: Boolean = false",
        "content: @Composable ColumnScope.() -> Unit"
      ],
      "kdoc": "Paper panel surface. Default content padding is 16.dp (web `wash-panel`).\nPass [flush] = true for edge-to-edge headers or dense layouts (web `wash-panel-flush`).",
      "excerpt": "@Composable\nfun WashPanel(\n    modifier: Modifier = Modifier,\n    flush: Boolean = false,\n    content: @Composable ColumnScope.() -> Unit,\n) {\n  …\n}"
    },
    "WashRadio": {
      "name": "WashRadio",
      "packagePath": "com.mariesta.menzies.washui.primitives",
      "relativeFile": "primitives/WashRadio.kt",
      "params": [
        "selected: Boolean",
        "onClick: () -> Unit",
        "modifier: Modifier = Modifier",
        "label: String? = null",
        "enabled: Boolean = true"
      ],
      "excerpt": "@Composable\nfun WashRadio(\n    selected: Boolean,\n    onClick: () -> Unit,\n    modifier: Modifier = Modifier,\n    label: String? = null,\n    enabled: Boolean = true,\n) {\n  …\n}"
    },
    "WashScaffold": {
      "name": "WashScaffold",
      "packagePath": "com.mariesta.menzies.washui.primitives",
      "relativeFile": "primitives/WashScaffold.kt",
      "params": [
        "modifier: Modifier = Modifier",
        "topBar: @Composable (() -> Unit)? = null",
        "contentPadding: PaddingValues = PaddingValues(0.dp)",
        "content: @Composable (PaddingValues) -> Unit"
      ],
      "kdoc": "Minimal Wash app shell: optional top bar stacked over scrollable content.\nReplaces Material3 Scaffold for gallery chrome without Material layout slots.\nDoes not paint a fill. Wrap with [com.mariesta.menzies.washui.components.WashBackground]\n(or [com.mariesta.menzies.washui.effects.pageWash] on [modifier]) for page atmosphere.\nFor web `WashShell` / `wash-shell-main` parity, pass\n`contentPadding = PaddingValues(horizontal = 16.dp, vertical = 24.dp)`.\nApplies [safeDrawingPadding] so top chrome clea",
      "excerpt": "@Composable\nfun WashScaffold(\n    modifier: Modifier = Modifier,\n    topBar: @Composable (() -> Unit)? = null,\n    contentPadding: PaddingValues = PaddingValues(0.dp),\n    content: @Composable (PaddingValues) -> Unit,\n) {\n  …\n}"
    },
    "WashSelect": {
      "name": "WashSelect",
      "packagePath": "com.mariesta.menzies.washui.primitives",
      "relativeFile": "primitives/WashSelect.kt",
      "params": [
        "value: String",
        "onValueChange: (String) -> Unit",
        "options: List<WashSelectOption>",
        "modifier: Modifier = Modifier",
        "label: String? = null",
        "hint: String? = null",
        "enabled: Boolean = true"
      ],
      "excerpt": "@Composable\nfun WashSelect(\n    value: String,\n    onValueChange: (String) -> Unit,\n    options: List<WashSelectOption>,\n    modifier: Modifier = Modifier,\n    label: String? = null,\n    hint: String? = null,\n    enabled: Boolean = true,\n) {\n  …\n}"
    },
    "WashSlider": {
      "name": "WashSlider",
      "packagePath": "com.mariesta.menzies.washui.primitives",
      "relativeFile": "primitives/WashSlider.kt",
      "params": [
        "value: Float",
        "onValueChange: (Float) -> Unit",
        "modifier: Modifier = Modifier",
        "valueRange: ClosedFloatingPointRange<Float> = 0f..1f",
        "enabled: Boolean = true",
        "activeColor: Color = Color.Unspecified",
        "inactiveColor: Color = Color.Unspecified",
        "thumbColor: Color = Color.Unspecified"
      ],
      "kdoc": "Foundation range control (no Material Slider).",
      "excerpt": "@Composable\nfun WashSlider(\n    value: Float,\n    onValueChange: (Float) -> Unit,\n    modifier: Modifier = Modifier,\n    valueRange: ClosedFloatingPointRange<Float> = 0f..1f,\n    enabled: Boolean = true,\n    activeColor: Color = Color.Unspecified,\n    inactiveColor: Color = Color.Unspecified,\n    thumbColor: Color = Color.Unspecified,\n) {\n  …\n}"
    },
    "WashText": {
      "name": "WashText",
      "packagePath": "com.mariesta.menzies.washui.primitives",
      "relativeFile": "primitives/WashText.kt",
      "params": [
        "text: String",
        "modifier: Modifier = Modifier",
        "color: Color = Color.Unspecified",
        "fontSize: TextUnit = TextUnit.Unspecified",
        "fontStyle: FontStyle? = null",
        "fontWeight: FontWeight? = null",
        "fontFamily: FontFamily? = null",
        "letterSpacing: TextUnit = TextUnit.Unspecified",
        "textAlign: TextAlign? = null",
        "lineHeight: TextUnit = TextUnit.Unspecified",
        "overflow: TextOverflow = TextOverflow.Clip",
        "softWrap: Boolean = true",
        "maxLines: Int = Int.MAX_VALUE",
        "style: TextStyle = TextStyle.Default"
      ],
      "kdoc": "Foundation [BasicText] styled with Wash colors. Replaces Material3 Text hosts.",
      "excerpt": "@Composable\nfun WashText(\n    text: String,\n    modifier: Modifier = Modifier,\n    color: Color = Color.Unspecified,\n    fontSize: TextUnit = TextUnit.Unspecified,\n    fontStyle: FontStyle? = null,\n    fontWeight: FontWeight? = null,\n    fontFamily: FontFamily? = null,\n    letterSpacing: TextUnit = TextUnit.Unspecified,\n    textAlign: TextAlign? = null,\n    lineHeight: TextUnit = TextUnit.Unspecified,\n    overflow: TextOverflow = TextOverflow.Clip,\n    softWrap: Boolean = true,\n    maxLines: Int = Int.MAX_VALUE,\n    style: TextStyle = TextStyle.Default,\n) {\n  …\n}"
    },
    "WashTextarea": {
      "name": "WashTextarea",
      "packagePath": "com.mariesta.menzies.washui.primitives",
      "relativeFile": "primitives/WashTextarea.kt",
      "params": [
        "value: String",
        "onValueChange: (String) -> Unit",
        "modifier: Modifier = Modifier",
        "label: String? = null",
        "hint: String? = null",
        "error: String? = null",
        "requiredMark: Boolean = false",
        "enabled: Boolean = true",
        "minLines: Int = 3",
        "placeholder: String? = null"
      ],
      "excerpt": "@Composable\nfun WashTextarea(\n    value: String,\n    onValueChange: (String) -> Unit,\n    modifier: Modifier = Modifier,\n    label: String? = null,\n    hint: String? = null,\n    error: String? = null,\n    requiredMark: Boolean = false,\n    enabled: Boolean = true,\n    minLines: Int = 3,\n    placeholder: String? = null,\n) {\n  …\n}"
    },
    "push": {
      "name": "push",
      "packagePath": "com.mariesta.menzies.washui.primitives",
      "relativeFile": "primitives/WashToast.kt",
      "params": [
        "message: String",
        "tone: WashToastTone = WashToastTone.Success"
      ],
      "excerpt": "fun push(message: String, tone: WashToastTone = WashToastTone.Success) {\n  …\n}"
    },
    "WashToast": {
      "name": "push",
      "packagePath": "com.mariesta.menzies.washui.primitives",
      "relativeFile": "primitives/WashToast.kt",
      "params": [
        "message: String",
        "tone: WashToastTone = WashToastTone.Success"
      ],
      "excerpt": "fun push(message: String, tone: WashToastTone = WashToastTone.Success) {\n  …\n}"
    },
    "WashToggle": {
      "name": "WashToggle",
      "packagePath": "com.mariesta.menzies.washui.primitives",
      "relativeFile": "primitives/WashToggle.kt",
      "params": [
        "checked: Boolean",
        "onCheckedChange: (Boolean) -> Unit",
        "modifier: Modifier = Modifier",
        "label: String? = null",
        "enabled: Boolean = true"
      ],
      "excerpt": "@Composable\nfun WashToggle(\n    checked: Boolean,\n    onCheckedChange: (Boolean) -> Unit,\n    modifier: Modifier = Modifier,\n    label: String? = null,\n    enabled: Boolean = true,\n) {\n  …\n}"
    },
    "WashTooltip": {
      "name": "WashTooltip",
      "packagePath": "com.mariesta.menzies.washui.primitives",
      "relativeFile": "primitives/WashTooltip.kt",
      "params": [
        "tip: String",
        "modifier: Modifier = Modifier",
        "side: WashTooltipSide = WashTooltipSide.Top",
        "tone: WashTooltipTone? = null",
        "prefer: WashTooltipSide? = null",
        "content: @Composable () -> Unit"
      ],
      "excerpt": "@Composable\nfun WashTooltip(\n    tip: String,\n    modifier: Modifier = Modifier,\n    side: WashTooltipSide = WashTooltipSide.Top,\n    tone: WashTooltipTone? = null,\n    prefer: WashTooltipSide? = null,\n    content: @Composable () -> Unit,\n) {\n  …\n}"
    },
    "WashTopBar": {
      "name": "WashTopBar",
      "packagePath": "com.mariesta.menzies.washui.primitives",
      "relativeFile": "primitives/WashTopBar.kt",
      "params": [
        "title: String",
        "modifier: Modifier = Modifier",
        "subtitle: String? = null",
        "navigationIcon: @Composable (() -> Unit)? = null",
        "brand: @Composable (() -> Unit)? = null",
        "actions: @Composable (RowScope.() -> Unit)? = null"
      ],
      "kdoc": "Wash navbar chrome: paper background, ink border, brand + actions.\nMirrors web recipe `navbar border-b border-ink-border/80 bg-base-100/80`.",
      "excerpt": "@Composable\nfun WashTopBar(\n    title: String,\n    modifier: Modifier = Modifier,\n    subtitle: String? = null,\n    navigationIcon: @Composable (() -> Unit)? = null,\n    /** Optional brand mark shown beside the title (e.g. shared launcher logo). */\n    brand: @Composable (() -> Unit)? = null,\n    actions: @Composable (RowScope.() -> Unit)? = null,\n) {\n  …\n}"
    },
    "BrushStrokeLoader": {
      "name": "BrushStrokeLoader",
      "packagePath": "com.mariesta.menzies.washui.components",
      "relativeFile": "components/StudioLoading.kt",
      "params": [
        "modifier: Modifier = Modifier"
      ],
      "excerpt": "@Composable\nfun BrushStrokeLoader(modifier: Modifier = Modifier) {\n  …\n}"
    },
    "StudioLoading": {
      "name": "BrushStrokeLoader",
      "packagePath": "com.mariesta.menzies.washui.components",
      "relativeFile": "components/StudioLoading.kt",
      "params": [
        "modifier: Modifier = Modifier"
      ],
      "excerpt": "@Composable\nfun BrushStrokeLoader(modifier: Modifier = Modifier) {\n  …\n}"
    },
    "WashAccordion": {
      "name": "WashAccordion",
      "packagePath": "com.mariesta.menzies.washui.components",
      "relativeFile": "components/WashAccordion.kt",
      "params": [
        "modifier: Modifier = Modifier",
        "name: String = \"wash-accordion\"",
        "content: @Composable () -> Unit"
      ],
      "excerpt": "@Composable\nfun WashAccordion(\n    modifier: Modifier = Modifier,\n    name: String = \"wash-accordion\",\n    content: @Composable () -> Unit,\n) {\n  …\n}"
    },
    "WashBackground": {
      "name": "WashBackground",
      "packagePath": "com.mariesta.menzies.washui.components",
      "relativeFile": "components/WashBackground.kt",
      "params": [
        "modifier: Modifier = Modifier",
        "grain: Boolean = false",
        "content: @Composable BoxScope.() -> Unit"
      ],
      "kdoc": "Page atmosphere: soft pigment radial washes over base-100 (web `page-wash`).\nWrap app shells so content sits on the same paper language as demo-web.\nGrain is off by default for smooth full-screen performance. Enable only for\ndecorative previews; the wash brushes are cached via [pageWash].",
      "excerpt": "@Composable\nfun WashBackground(\n    modifier: Modifier = Modifier,\n    grain: Boolean = false,\n    content: @Composable BoxScope.() -> Unit,\n) {\n  …\n}"
    },
    "WashCard": {
      "name": "WashCard",
      "packagePath": "com.mariesta.menzies.washui.components",
      "relativeFile": "components/WashCard.kt",
      "params": [
        "modifier: Modifier = Modifier",
        "compact: Boolean = false",
        "bordered: Boolean = true",
        "content: @Composable ColumnScope.() -> Unit"
      ],
      "excerpt": "@Composable\nfun WashCard(\n    modifier: Modifier = Modifier,\n    compact: Boolean = false,\n    bordered: Boolean = true,\n    content: @Composable ColumnScope.() -> Unit,\n) {\n  …\n}"
    },
    "WashTabs": {
      "name": "WashTabs",
      "packagePath": "com.mariesta.menzies.washui.components",
      "relativeFile": "components/WashTabs.kt",
      "params": [
        "defaultValue: String",
        "modifier: Modifier = Modifier",
        "boxed: Boolean = false",
        "content: @Composable () -> Unit"
      ],
      "excerpt": "@Composable\nfun WashTabs(\n    defaultValue: String,\n    modifier: Modifier = Modifier,\n    boxed: Boolean = false,\n    content: @Composable () -> Unit,\n) {\n  …\n}"
    },
    "WashThemeSwitcher": {
      "name": "WashThemeSwitcher",
      "packagePath": "com.mariesta.menzies.washui.components",
      "relativeFile": "components/WashThemeSwitcher.kt",
      "params": [
        "modifier: Modifier = Modifier"
      ],
      "excerpt": "@Composable\nfun WashThemeSwitcher(modifier: Modifier = Modifier) {\n  …\n}"
    },
    "WashProvider": {
      "name": "WashProvider",
      "packagePath": "com.mariesta.menzies.washui",
      "relativeFile": "WashProvider.kt",
      "params": [
        "defaultPigment: WashPigment? = null",
        "defaultMode: WashMode? = null",
        "followSystemMode: Boolean = true",
        "content: @Composable () -> Unit"
      ],
      "excerpt": "@Composable\nfun WashProvider(\n    defaultPigment: WashPigment? = null,\n    defaultMode: WashMode? = null,\n    followSystemMode: Boolean = true,\n    content: @Composable () -> Unit,\n) {\n  …\n}"
    },
    "WashIcon": {
      "name": "WashIcon",
      "packagePath": "com.mariesta.menzies.washui.icons",
      "relativeFile": "icons/WashIcons.kt",
      "params": [
        "imageVector: ImageVector",
        "contentDescription: String?",
        "modifier: Modifier = Modifier",
        "tint: Color = Color.Unspecified",
        "size: Dp = 24.dp"
      ],
      "kdoc": "Marker object for Lucide ImageVectors (lucide-react 1.28.0 paths). */\npublic object LucideIcons\n\n/** Marker object for Simple Icons brand ImageVectors. */\npublic object BrandIcons\n\n/**\nRenders a Wash icon via Foundation [Image] + vector painter (no Material Icon host).\nBrand marks keep baked-in Simple Icons colors when [tint] is [Color.Unspecified];\nLucide strokes tint when a color is supplied.",
      "excerpt": "@Composable\npublic fun WashIcon(\n    imageVector: ImageVector,\n    contentDescription: String?,\n    modifier: Modifier = Modifier,\n    tint: Color = Color.Unspecified,\n    size: Dp = 24.dp,\n) {\n  …\n}"
    },
    "WashIcons": {
      "name": "WashIcon",
      "packagePath": "com.mariesta.menzies.washui.icons",
      "relativeFile": "icons/WashIcons.kt",
      "params": [
        "imageVector: ImageVector",
        "contentDescription: String?",
        "modifier: Modifier = Modifier",
        "tint: Color = Color.Unspecified",
        "size: Dp = 24.dp"
      ],
      "kdoc": "Marker object for Lucide ImageVectors (lucide-react 1.28.0 paths). */\npublic object LucideIcons\n\n/** Marker object for Simple Icons brand ImageVectors. */\npublic object BrandIcons\n\n/**\nRenders a Wash icon via Foundation [Image] + vector painter (no Material Icon host).\nBrand marks keep baked-in Simple Icons colors when [tint] is [Color.Unspecified];\nLucide strokes tint when a color is supplied.",
      "excerpt": "@Composable\npublic fun WashIcon(\n    imageVector: ImageVector,\n    contentDescription: String?,\n    modifier: Modifier = Modifier,\n    tint: Color = Color.Unspecified,\n    size: Dp = 24.dp,\n) {\n  …\n}"
    }
  }
}
