// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.lucide

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.LucideIcons

private var _bell: ImageVector? = null

public val LucideIcons.Bell: ImageVector
    get() {
        _bell?.let { return it }
        return ImageVector.Builder(
            name = "Lucide.Bell",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(10.268f, 21f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 13.732f, y1 = 21f)
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(3.262f, 15.326f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 4f, y1 = 17f)
            horizontalLineTo(20f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 20.74f, y1 = 15.327f)
            curveTo(19.41f, 13.956f, 18f, 12.499f, 18f, 8f)
            arcTo(horizontalEllipseRadius = 6f, verticalEllipseRadius = 6f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 6f, y1 = 8f)
            curveTo(6f, 12.499f, 4.589f, 13.956f, 3.262f, 15.326f)
        }
        }.build().also { _bell = it }
    }
