// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.lucide

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.LucideIcons

private var _bookOpen: ImageVector? = null

public val LucideIcons.BookOpen: ImageVector
    get() {
        _bookOpen?.let { return it }
        return ImageVector.Builder(
            name = "Lucide.BookOpen",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(12f, 5f)
            verticalLineTo(21f)
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(20.001f, 19f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 22f, y1 = 17f)
            verticalLineTo(5f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 20.001f, y1 = 3f)
            lineTo(16f, 3.002f)
            arcTo(horizontalEllipseRadius = 5f, verticalEllipseRadius = 5f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 12f, y1 = 5f)
            arcTo(horizontalEllipseRadius = 5f, verticalEllipseRadius = 5f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 8f, y1 = 3f)
            horizontalLineTo(4f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 2f, y1 = 5f)
            verticalLineTo(17f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 3.999f, y1 = 19f)
            horizontalLineTo(8f)
            arcTo(horizontalEllipseRadius = 5f, verticalEllipseRadius = 5f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 12f, y1 = 21f)
            arcTo(horizontalEllipseRadius = 5f, verticalEllipseRadius = 5f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 16f, y1 = 19f)
            close()
        }
        }.build().also { _bookOpen = it }
    }
