// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.lucide

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.LucideIcons

private var _chartPie: ImageVector? = null

public val LucideIcons.ChartPie: ImageVector
    get() {
        _chartPie?.let { return it }
        return ImageVector.Builder(
            name = "Lucide.ChartPie",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(21f, 12f)
            curveTo(21.552f, 12f, 22.005f, 11.551f, 21.95f, 11.002f)
            arcTo(horizontalEllipseRadius = 10f, verticalEllipseRadius = 10f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 12.997f, y1 = 2.051f)
            curveTo(12.447f, 1.996f, 11.999f, 2.449f, 11.999f, 3.001f)
            verticalLineTo(11.001f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 12.999f, y1 = 12.001f)
            close()
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(21.21f, 15.89f)
            arcTo(horizontalEllipseRadius = 10f, verticalEllipseRadius = 10f, theta = 0f, isMoreThanHalf = true, isPositiveArc = true, x1 = 8f, y1 = 2.83f)
        }
        }.build().also { _chartPie = it }
    }
