// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.lucide

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.LucideIcons

private var _chartScatter: ImageVector? = null

public val LucideIcons.ChartScatter: ImageVector
    get() {
        _chartScatter?.let { return it }
        return ImageVector.Builder(
            name = "Lucide.ChartScatter",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
        path(
            fill = SolidColor(Color.Black),
            stroke = null,
        ) {
            moveTo(7f, 7.5f)
            arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 8f, y1 = 7.5f)
            arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 7f, y1 = 7.5f)
        }
        path(
            fill = SolidColor(Color.Black),
            stroke = null,
        ) {
            moveTo(18f, 5.5f)
            arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 19f, y1 = 5.5f)
            arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 18f, y1 = 5.5f)
        }
        path(
            fill = SolidColor(Color.Black),
            stroke = null,
        ) {
            moveTo(11f, 11.5f)
            arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 12f, y1 = 11.5f)
            arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 11f, y1 = 11.5f)
        }
        path(
            fill = SolidColor(Color.Black),
            stroke = null,
        ) {
            moveTo(7f, 16.5f)
            arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 8f, y1 = 16.5f)
            arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 7f, y1 = 16.5f)
        }
        path(
            fill = SolidColor(Color.Black),
            stroke = null,
        ) {
            moveTo(17f, 14.5f)
            arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 18f, y1 = 14.5f)
            arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 17f, y1 = 14.5f)
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(3f, 3f)
            verticalLineTo(19f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 5f, y1 = 21f)
            horizontalLineTo(21f)
        }
        }.build().also { _chartScatter = it }
    }
