// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.lucide

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.LucideIcons

private var _droplets: ImageVector? = null

public val LucideIcons.Droplets: ImageVector
    get() {
        _droplets?.let { return it }
        return ImageVector.Builder(
            name = "Lucide.Droplets",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(7f, 16.3f)
            curveTo(9.2f, 16.3f, 11f, 14.47f, 11f, 12.25f)
            curveTo(11f, 11.09f, 10.43f, 9.99f, 9.29f, 9.06f)
            curveTo(8.15f, 8.13f, 7.29f, 6.75f, 7f, 5.3f)
            curveTo(6.71f, 6.75f, 5.86f, 8.14f, 4.71f, 9.06f)
            curveTo(3.56f, 9.98f, 3f, 11.1f, 3f, 12.25f)
            curveTo(3f, 14.47f, 4.8f, 16.3f, 7f, 16.3f)
            close()
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(12.56f, 6.6f)
            arcTo(horizontalEllipseRadius = 10.97f, verticalEllipseRadius = 10.97f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 14f, y1 = 3.02f)
            curveTo(14.5f, 5.52f, 16f, 7.92f, 18f, 9.52f)
            curveTo(20f, 11.12f, 21f, 13.02f, 21f, 15.02f)
            arcTo(horizontalEllipseRadius = 6.98f, verticalEllipseRadius = 6.98f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 9.09f, y1 = 19.99f)
        }
        }.build().also { _droplets = it }
    }
