// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.lucide

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.LucideIcons

private var _eyeOff: ImageVector? = null

public val LucideIcons.EyeOff: ImageVector
    get() {
        _eyeOff?.let { return it }
        return ImageVector.Builder(
            name = "Lucide.EyeOff",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(10.733f, 5.076f)
            arcTo(horizontalEllipseRadius = 10.744f, verticalEllipseRadius = 10.744f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 21.938f, y1 = 11.651f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 21.938f, y1 = 12.347f)
            arcTo(horizontalEllipseRadius = 10.747f, verticalEllipseRadius = 10.747f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 20.494f, y1 = 14.837f)
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(14.084f, 14.158f)
            arcTo(horizontalEllipseRadius = 3f, verticalEllipseRadius = 3f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 9.842f, y1 = 9.916f)
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(17.479f, 17.499f)
            arcTo(horizontalEllipseRadius = 10.75f, verticalEllipseRadius = 10.75f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 2.062f, y1 = 12.348f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 2.062f, y1 = 11.652f)
            arcTo(horizontalEllipseRadius = 10.75f, verticalEllipseRadius = 10.75f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 6.508f, y1 = 6.509f)
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(2f, 2f)
            lineTo(22f, 22f)
        }
        }.build().also { _eyeOff = it }
    }
