// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.lucide

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.LucideIcons

private var _heart: ImageVector? = null

public val LucideIcons.Heart: ImageVector
    get() {
        _heart?.let { return it }
        return ImageVector.Builder(
            name = "Lucide.Heart",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(2f, 9.5f)
            arcTo(horizontalEllipseRadius = 5.5f, verticalEllipseRadius = 5.5f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 11.591f, y1 = 5.824f)
            arcTo(horizontalEllipseRadius = 0.56f, verticalEllipseRadius = 0.56f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 12.409f, y1 = 5.824f)
            arcTo(horizontalEllipseRadius = 5.49f, verticalEllipseRadius = 5.49f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 22f, y1 = 9.5f)
            curveTo(22f, 11.79f, 20.5f, 13.5f, 19f, 15f)
            lineTo(13.508f, 20.313f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 10.508f, y1 = 20.332f)
            lineTo(5f, 15f)
            curveTo(3.5f, 13.5f, 2f, 11.8f, 2f, 9.5f)
        }
        }.build().also { _heart = it }
    }
