// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.lucide

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.LucideIcons

private var _history: ImageVector? = null

public val LucideIcons.History: ImageVector
    get() {
        _history?.let { return it }
        return ImageVector.Builder(
            name = "Lucide.History",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(3f, 12f)
            arcTo(horizontalEllipseRadius = 9f, verticalEllipseRadius = 9f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 12f, y1 = 3f)
            arcTo(horizontalEllipseRadius = 9.75f, verticalEllipseRadius = 9.75f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 5.26f, y1 = 5.74f)
            lineTo(3f, 8f)
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(3f, 3f)
            verticalLineTo(8f)
            horizontalLineTo(8f)
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(12f, 7f)
            verticalLineTo(12f)
            lineTo(16f, 14f)
        }
        }.build().also { _history = it }
    }
