// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.lucide

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.LucideIcons

private var _keyRound: ImageVector? = null

public val LucideIcons.KeyRound: ImageVector
    get() {
        _keyRound?.let { return it }
        return ImageVector.Builder(
            name = "Lucide.KeyRound",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(2.586f, 17.414f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 2f, y1 = 18.828f)
            verticalLineTo(21f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 3f, y1 = 22f)
            horizontalLineTo(6f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 7f, y1 = 21f)
            verticalLineTo(20f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 8f, y1 = 19f)
            horizontalLineTo(9f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 10f, y1 = 18f)
            verticalLineTo(17f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 11f, y1 = 16f)
            horizontalLineTo(11.172f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 12.586f, y1 = 15.414f)
            lineTo(13.4f, 14.6f)
            arcTo(horizontalEllipseRadius = 6.5f, verticalEllipseRadius = 6.5f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 9.4f, y1 = 10.6f)
            close()
        }
        path(
            fill = SolidColor(Color.Black),
            stroke = null,
        ) {
            moveTo(16f, 7.5f)
            arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 17f, y1 = 7.5f)
            arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 16f, y1 = 7.5f)
        }
        }.build().also { _keyRound = it }
    }
