// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.lucide

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.LucideIcons

private var _layers: ImageVector? = null

public val LucideIcons.Layers: ImageVector
    get() {
        _layers?.let { return it }
        return ImageVector.Builder(
            name = "Lucide.Layers",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(12.83f, 2.18f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 11.17f, y1 = 2.18f)
            lineTo(2.6f, 6.08f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 2.6f, y1 = 7.91f)
            lineTo(11.18f, 11.82f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 12.84f, y1 = 11.82f)
            lineTo(21.42f, 7.92f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 21.42f, y1 = 6.09f)
            close()
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(2f, 12f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 2.58f, y1 = 12.91f)
            lineTo(11.18f, 16.82f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 12.83f, y1 = 16.82f)
            lineTo(21.41f, 12.92f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 22f, y1 = 12f)
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(2f, 17f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 2.58f, y1 = 17.91f)
            lineTo(11.18f, 21.82f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 12.83f, y1 = 21.82f)
            lineTo(21.41f, 17.92f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 22f, y1 = 17f)
        }
        }.build().also { _layers = it }
    }
