// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.lucide

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.LucideIcons

private var _layoutDashboard: ImageVector? = null

public val LucideIcons.LayoutDashboard: ImageVector
    get() {
        _layoutDashboard?.let { return it }
        return ImageVector.Builder(
            name = "Lucide.LayoutDashboard",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(4f, 3f)
            horizontalLineTo(9f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 10f, y1 = 4f)
            verticalLineTo(11f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 9f, y1 = 12f)
            horizontalLineTo(4f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 3f, y1 = 11f)
            verticalLineTo(4f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 4f, y1 = 3f)
            close()
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(15f, 3f)
            horizontalLineTo(20f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 21f, y1 = 4f)
            verticalLineTo(7f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 20f, y1 = 8f)
            horizontalLineTo(15f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 14f, y1 = 7f)
            verticalLineTo(4f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 15f, y1 = 3f)
            close()
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(15f, 12f)
            horizontalLineTo(20f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 21f, y1 = 13f)
            verticalLineTo(20f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 20f, y1 = 21f)
            horizontalLineTo(15f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 14f, y1 = 20f)
            verticalLineTo(13f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 15f, y1 = 12f)
            close()
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(4f, 16f)
            horizontalLineTo(9f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 10f, y1 = 17f)
            verticalLineTo(20f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 9f, y1 = 21f)
            horizontalLineTo(4f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 3f, y1 = 20f)
            verticalLineTo(17f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 4f, y1 = 16f)
            close()
        }
        }.build().also { _layoutDashboard = it }
    }
