// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.lucide

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.LucideIcons

private var _messagesSquare: ImageVector? = null

public val LucideIcons.MessagesSquare: ImageVector
    get() {
        _messagesSquare?.let { return it }
        return ImageVector.Builder(
            name = "Lucide.MessagesSquare",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(16f, 10f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 14f, y1 = 12f)
            horizontalLineTo(6.828f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 5.414f, y1 = 12.586f)
            lineTo(3.212f, 14.788f)
            arcTo(horizontalEllipseRadius = 0.71f, verticalEllipseRadius = 0.71f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 2f, y1 = 14.286f)
            verticalLineTo(4f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 4f, y1 = 2f)
            horizontalLineTo(14f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 16f, y1 = 4f)
            close()
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(20f, 9f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 22f, y1 = 11f)
            verticalLineTo(21.286f)
            arcTo(horizontalEllipseRadius = 0.71f, verticalEllipseRadius = 0.71f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 20.788f, y1 = 21.788f)
            lineTo(18.586f, 19.586f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 17.172f, y1 = 19f)
            horizontalLineTo(10f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 8f, y1 = 17f)
            verticalLineTo(16f)
        }
        }.build().also { _messagesSquare = it }
    }
