// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.lucide

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.LucideIcons

private var _palette: ImageVector? = null

public val LucideIcons.Palette: ImageVector
    get() {
        _palette?.let { return it }
        return ImageVector.Builder(
            name = "Lucide.Palette",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(12f, 22f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 12f, y1 = 2f)
            arcTo(horizontalEllipseRadius = 10f, verticalEllipseRadius = 9f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 22f, y1 = 11f)
            arcTo(horizontalEllipseRadius = 5f, verticalEllipseRadius = 5f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 17f, y1 = 16f)
            horizontalLineTo(14.75f)
            arcTo(horizontalEllipseRadius = 1.75f, verticalEllipseRadius = 1.75f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 13.35f, y1 = 18.8f)
            lineTo(13.65f, 19.2f)
            arcTo(horizontalEllipseRadius = 1.75f, verticalEllipseRadius = 1.75f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 12.25f, y1 = 22f)
            close()
        }
        path(
            fill = SolidColor(Color.Black),
            stroke = null,
        ) {
            moveTo(13f, 6.5f)
            arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 14f, y1 = 6.5f)
            arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 13f, y1 = 6.5f)
        }
        path(
            fill = SolidColor(Color.Black),
            stroke = null,
        ) {
            moveTo(17f, 10.5f)
            arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 18f, y1 = 10.5f)
            arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 17f, y1 = 10.5f)
        }
        path(
            fill = SolidColor(Color.Black),
            stroke = null,
        ) {
            moveTo(6f, 12.5f)
            arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 7f, y1 = 12.5f)
            arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 6f, y1 = 12.5f)
        }
        path(
            fill = SolidColor(Color.Black),
            stroke = null,
        ) {
            moveTo(8f, 7.5f)
            arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 9f, y1 = 7.5f)
            arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 8f, y1 = 7.5f)
        }
        }.build().also { _palette = it }
    }
