// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.lucide

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.LucideIcons

private var _radio: ImageVector? = null

public val LucideIcons.Radio: ImageVector
    get() {
        _radio?.let { return it }
        return ImageVector.Builder(
            name = "Lucide.Radio",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(16.247f, 7.761f)
            arcTo(horizontalEllipseRadius = 6f, verticalEllipseRadius = 6f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 16.247f, y1 = 16.239f)
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(19.075f, 4.933f)
            arcTo(horizontalEllipseRadius = 10f, verticalEllipseRadius = 10f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 19.075f, y1 = 19.067f)
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(4.925f, 19.067f)
            arcTo(horizontalEllipseRadius = 10f, verticalEllipseRadius = 10f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 4.925f, y1 = 4.933f)
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(7.753f, 16.239f)
            arcTo(horizontalEllipseRadius = 6f, verticalEllipseRadius = 6f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 7.753f, y1 = 7.761f)
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(10f, 12f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 14f, y1 = 12f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 10f, y1 = 12f)
        }
        }.build().also { _radio = it }
    }
