// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.lucide

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.LucideIcons

private var _rotateCw: ImageVector? = null

public val LucideIcons.RotateCw: ImageVector
    get() {
        _rotateCw?.let { return it }
        return ImageVector.Builder(
            name = "Lucide.RotateCw",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(21f, 12f)
            arcTo(horizontalEllipseRadius = 9f, verticalEllipseRadius = 9f, theta = 0f, isMoreThanHalf = true, isPositiveArc = true, x1 = 12f, y1 = 3f)
            curveTo(14.52f, 3f, 16.93f, 4f, 18.74f, 5.74f)
            lineTo(21f, 8f)
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(21f, 3f)
            verticalLineTo(8f)
            horizontalLineTo(16f)
        }
        }.build().also { _rotateCw = it }
    }
