// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.lucide

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.LucideIcons

private var _search: ImageVector? = null

public val LucideIcons.Search: ImageVector
    get() {
        _search?.let { return it }
        return ImageVector.Builder(
            name = "Lucide.Search",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(21f, 21f)
            lineTo(16.66f, 16.66f)
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(3f, 11f)
            arcTo(horizontalEllipseRadius = 8f, verticalEllipseRadius = 8f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 19f, y1 = 11f)
            arcTo(horizontalEllipseRadius = 8f, verticalEllipseRadius = 8f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 3f, y1 = 11f)
        }
        }.build().also { _search = it }
    }
