// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.lucide

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.LucideIcons

private var _settings: ImageVector? = null

public val LucideIcons.Settings: ImageVector
    get() {
        _settings?.let { return it }
        return ImageVector.Builder(
            name = "Lucide.Settings",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(9.671f, 4.136f)
            arcTo(horizontalEllipseRadius = 2.34f, verticalEllipseRadius = 2.34f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 14.33f, y1 = 4.136f)
            arcTo(horizontalEllipseRadius = 2.34f, verticalEllipseRadius = 2.34f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 17.649f, y1 = 6.051f)
            arcTo(horizontalEllipseRadius = 2.34f, verticalEllipseRadius = 2.34f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 19.979f, y1 = 10.084f)
            arcTo(horizontalEllipseRadius = 2.34f, verticalEllipseRadius = 2.34f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 19.979f, y1 = 13.915f)
            arcTo(horizontalEllipseRadius = 2.34f, verticalEllipseRadius = 2.34f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 17.649f, y1 = 17.948f)
            arcTo(horizontalEllipseRadius = 2.34f, verticalEllipseRadius = 2.34f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 14.33f, y1 = 19.863f)
            arcTo(horizontalEllipseRadius = 2.34f, verticalEllipseRadius = 2.34f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 9.671f, y1 = 19.863f)
            arcTo(horizontalEllipseRadius = 2.34f, verticalEllipseRadius = 2.34f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 6.351f, y1 = 17.948f)
            arcTo(horizontalEllipseRadius = 2.34f, verticalEllipseRadius = 2.34f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 4.021f, y1 = 13.915f)
            arcTo(horizontalEllipseRadius = 2.34f, verticalEllipseRadius = 2.34f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 4.021f, y1 = 10.084f)
            arcTo(horizontalEllipseRadius = 2.34f, verticalEllipseRadius = 2.34f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 6.35f, y1 = 6.051f)
            arcTo(horizontalEllipseRadius = 2.34f, verticalEllipseRadius = 2.34f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 9.669f, y1 = 4.136f)
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(9f, 12f)
            arcTo(horizontalEllipseRadius = 3f, verticalEllipseRadius = 3f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 15f, y1 = 12f)
            arcTo(horizontalEllipseRadius = 3f, verticalEllipseRadius = 3f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 9f, y1 = 12f)
        }
        }.build().also { _settings = it }
    }
