// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.lucide

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.LucideIcons

private var _shieldCheck: ImageVector? = null

public val LucideIcons.ShieldCheck: ImageVector
    get() {
        _shieldCheck?.let { return it }
        return ImageVector.Builder(
            name = "Lucide.ShieldCheck",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(20f, 13f)
            curveTo(20f, 18f, 16.5f, 20.5f, 12.34f, 21.95f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 11.67f, y1 = 21.94f)
            curveTo(7.5f, 20.5f, 4f, 18f, 4f, 13f)
            verticalLineTo(6f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 5f, y1 = 5f)
            curveTo(7f, 5f, 9.5f, 3.8f, 11.24f, 2.28f)
            arcTo(horizontalEllipseRadius = 1.17f, verticalEllipseRadius = 1.17f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 12.76f, y1 = 2.28f)
            curveTo(14.51f, 3.81f, 17f, 5f, 19f, 5f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 20f, y1 = 6f)
            close()
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(9f, 12f)
            lineTo(11f, 14f)
            lineTo(15f, 10f)
        }
        }.build().also { _shieldCheck = it }
    }
