// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.lucide

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.LucideIcons

private var _sparkles: ImageVector? = null

public val LucideIcons.Sparkles: ImageVector
    get() {
        _sparkles?.let { return it }
        return ImageVector.Builder(
            name = "Lucide.Sparkles",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(11.017f, 2.814f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 12.983f, y1 = 2.814f)
            lineTo(14.034f, 8.372f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 15.628f, y1 = 9.966f)
            lineTo(21.186f, 11.017f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 21.186f, y1 = 12.983f)
            lineTo(15.628f, 14.034f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 14.034f, y1 = 15.628f)
            lineTo(12.983f, 21.186f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 11.017f, y1 = 21.186f)
            lineTo(9.966f, 15.628f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 8.372f, y1 = 14.034f)
            lineTo(2.814f, 12.983f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 2.814f, y1 = 11.017f)
            lineTo(8.372f, 9.966f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 9.966f, y1 = 8.372f)
            close()
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(20f, 2f)
            verticalLineTo(6f)
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(22f, 4f)
            horizontalLineTo(18f)
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(2f, 20f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 6f, y1 = 20f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 2f, y1 = 20f)
        }
        }.build().also { _sparkles = it }
    }
