// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.lucide

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.LucideIcons

private var _squareMousePointer: ImageVector? = null

public val LucideIcons.SquareMousePointer: ImageVector
    get() {
        _squareMousePointer?.let { return it }
        return ImageVector.Builder(
            name = "Lucide.SquareMousePointer",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(12.034f, 12.681f)
            arcTo(horizontalEllipseRadius = 0.498f, verticalEllipseRadius = 0.498f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 12.681f, y1 = 12.034f)
            lineTo(21.681f, 15.534f)
            arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 21.648f, y1 = 16.477f)
            lineTo(18.204f, 17.545f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 17.544f, y1 = 18.205f)
            lineTo(16.477f, 21.648f)
            arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 15.534f, y1 = 21.681f)
            close()
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(21f, 11f)
            verticalLineTo(5f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 19f, y1 = 3f)
            horizontalLineTo(5f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 3f, y1 = 5f)
            verticalLineTo(19f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 5f, y1 = 21f)
            horizontalLineTo(11f)
        }
        }.build().also { _squareMousePointer = it }
    }
