// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.lucide

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.LucideIcons

private var _star: ImageVector? = null

public val LucideIcons.Star: ImageVector
    get() {
        _star?.let { return it }
        return ImageVector.Builder(
            name = "Lucide.Star",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(11.525f, 2.295f)
            arcTo(horizontalEllipseRadius = 0.53f, verticalEllipseRadius = 0.53f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 12.475f, y1 = 2.295f)
            lineTo(14.785f, 6.974f)
            arcTo(horizontalEllipseRadius = 2.123f, verticalEllipseRadius = 2.123f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 16.38f, y1 = 8.134f)
            lineTo(21.546f, 8.89f)
            arcTo(horizontalEllipseRadius = 0.53f, verticalEllipseRadius = 0.53f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 21.84f, y1 = 9.794f)
            lineTo(18.104f, 13.432f)
            arcTo(horizontalEllipseRadius = 2.123f, verticalEllipseRadius = 2.123f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 17.493f, y1 = 15.31f)
            lineTo(18.375f, 20.45f)
            arcTo(horizontalEllipseRadius = 0.53f, verticalEllipseRadius = 0.53f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 17.604f, y1 = 21.01f)
            lineTo(12.986f, 18.582f)
            arcTo(horizontalEllipseRadius = 2.122f, verticalEllipseRadius = 2.122f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 11.013f, y1 = 18.582f)
            lineTo(6.396f, 21.01f)
            arcTo(horizontalEllipseRadius = 0.53f, verticalEllipseRadius = 0.53f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 5.626f, y1 = 20.45f)
            lineTo(6.507f, 15.311f)
            arcTo(horizontalEllipseRadius = 2.122f, verticalEllipseRadius = 2.122f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 5.896f, y1 = 13.432f)
            lineTo(2.16f, 9.795f)
            arcTo(horizontalEllipseRadius = 0.53f, verticalEllipseRadius = 0.53f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 2.454f, y1 = 8.889f)
            lineTo(7.619f, 8.134f)
            arcTo(horizontalEllipseRadius = 2.122f, verticalEllipseRadius = 2.122f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 9.216f, y1 = 6.974f)
            close()
        }
        }.build().also { _star = it }
    }
