// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.lucide

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.LucideIcons

private var _tag: ImageVector? = null

public val LucideIcons.Tag: ImageVector
    get() {
        _tag?.let { return it }
        return ImageVector.Builder(
            name = "Lucide.Tag",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(12.586f, 2.586f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 11.172f, y1 = 2f)
            horizontalLineTo(4f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 2f, y1 = 4f)
            verticalLineTo(11.172f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 2.586f, y1 = 12.586f)
            lineTo(11.29f, 21.29f)
            arcTo(horizontalEllipseRadius = 2.426f, verticalEllipseRadius = 2.426f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 14.71f, y1 = 21.29f)
            lineTo(21.29f, 14.71f)
            arcTo(horizontalEllipseRadius = 2.426f, verticalEllipseRadius = 2.426f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 21.29f, y1 = 11.29f)
            close()
        }
        path(
            fill = SolidColor(Color.Black),
            stroke = null,
        ) {
            moveTo(7f, 7.5f)
            arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 8f, y1 = 7.5f)
            arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 7f, y1 = 7.5f)
        }
        }.build().also { _tag = it }
    }
