// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.lucide

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.LucideIcons

private var _tags: ImageVector? = null

public val LucideIcons.Tags: ImageVector
    get() {
        _tags?.let { return it }
        return ImageVector.Builder(
            name = "Lucide.Tags",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(13.172f, 2f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 14.586f, y1 = 2.586f)
            lineTo(21.296f, 9.296f)
            arcTo(horizontalEllipseRadius = 2.4f, verticalEllipseRadius = 2.4f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 21.296f, y1 = 12.704f)
            lineTo(16.704f, 17.296f)
            arcTo(horizontalEllipseRadius = 2.4f, verticalEllipseRadius = 2.4f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 13.296f, y1 = 17.296f)
            lineTo(6.586f, 10.586f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 6f, y1 = 9.172f)
            verticalLineTo(3f)
            arcTo(horizontalEllipseRadius = 1f, verticalEllipseRadius = 1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 7f, y1 = 2f)
            close()
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(2f, 7f)
            verticalLineTo(13.172f)
            arcTo(horizontalEllipseRadius = 2f, verticalEllipseRadius = 2f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 2.586f, y1 = 14.586f)
            lineTo(9.296f, 21.296f)
            arcTo(horizontalEllipseRadius = 2.4f, verticalEllipseRadius = 2.4f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 12.487f, y1 = 21.489f)
        }
        path(
            fill = SolidColor(Color.Black),
            stroke = null,
        ) {
            moveTo(10f, 6.5f)
            arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 11f, y1 = 6.5f)
            arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0f, isMoreThanHalf = true, isPositiveArc = false, x1 = 10f, y1 = 6.5f)
        }
        }.build().also { _tags = it }
    }
