// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.lucide

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.LucideIcons

private var _waves: ImageVector? = null

public val LucideIcons.Waves: ImageVector
    get() {
        _waves?.let { return it }
        return ImageVector.Builder(
            name = "Lucide.Waves",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(2f, 12f)
            quadTo(4.5f, 14f, 7f, 12f)
            quadTo(9.5f, 10f, 12f, 12f)
            quadTo(14.5f, 14f, 17f, 12f)
            quadTo(19.5f, 10f, 22f, 12f)
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(2f, 19f)
            quadTo(4.5f, 21f, 7f, 19f)
            quadTo(9.5f, 17f, 12f, 19f)
            quadTo(14.5f, 21f, 17f, 19f)
            quadTo(19.5f, 17f, 22f, 19f)
        }
        path(
            fill = SolidColor(Color.Transparent),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        ) {
            moveTo(2f, 5f)
            quadTo(4.5f, 7f, 7f, 5f)
            quadTo(9.5f, 3f, 12f, 5f)
            quadTo(14.5f, 7f, 17f, 5f)
            quadTo(19.5f, 3f, 22f, 5f)
        }
        }.build().also { _waves = it }
    }
