// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.brands

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.BrandIcons

private var _angular: ImageVector? = null

/** Angular brand mark (Simple Icons). */
public val BrandIcons.Angular: ImageVector
    get() {
        _angular?.let { return it }
        return ImageVector.Builder(
            name = "Brand.Angular",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(
                fill = SolidColor(Color(0xFF0F0F11)),
                stroke = null,
            ) {
            moveTo(16.712f, 17.711f)
            horizontalLineTo(7.288f)
            lineTo(6.084f, 20.627f)
            lineTo(12f, 24f)
            lineTo(17.916f, 20.627f)
            lineTo(16.712f, 17.711f)
            close()
            moveTo(14.692f, 0f)
            lineTo(22.524f, 16.855f)
            lineTo(23.338f, 3.999f)
            lineTo(14.692f, 0f)
            close()
            moveTo(9.308f, 0f)
            lineTo(0.662f, 3.999f)
            lineTo(1.476f, 16.855f)
            lineTo(9.308f, 0f)
            close()
            moveTo(8.903f, 13.93f)
            horizontalLineTo(15.101f)
            lineTo(12f, 6.396f)
            lineTo(8.903f, 13.93f)
            close()
            }
        }.build().also { _angular = it }
    }
