// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.brands

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.BrandIcons

private var _astro: ImageVector? = null

/** Astro brand mark (Simple Icons). */
public val BrandIcons.Astro: ImageVector
    get() {
        _astro?.let { return it }
        return ImageVector.Builder(
            name = "Brand.Astro",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(
                fill = SolidColor(Color(0xFFBC52EE)),
                stroke = null,
            ) {
            moveTo(8.358f, 20.162f)
            curveTo(7.172f, 19.092f, 6.826f, 16.846f, 7.32f, 15.218f)
            curveTo(8.176f, 16.244f, 9.363f, 16.57f, 10.592f, 16.753f)
            curveTo(12.489f, 17.036f, 14.352f, 16.93f, 16.114f, 16.075f)
            curveTo(16.316f, 15.977f, 16.502f, 15.846f, 16.722f, 15.715f)
            curveTo(16.888f, 16.188f, 16.931f, 16.665f, 16.873f, 17.152f)
            curveTo(16.733f, 18.337f, 16.135f, 19.252f, 15.185f, 19.946f)
            curveTo(14.805f, 20.223f, 14.403f, 20.471f, 14.01f, 20.733f)
            curveTo(12.805f, 21.537f, 12.479f, 22.48f, 12.932f, 23.852f)
            lineTo(12.976f, 24f)
            arcTo(horizontalEllipseRadius = 3.158f, verticalEllipseRadius = 3.158f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 11.569f, y1 = 22.812f)
            arcTo(horizontalEllipseRadius = 3.31f, verticalEllipseRadius = 3.31f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 11.025f, y1 = 20.997f)
            curveTo(11.021f, 20.677f, 11.021f, 20.355f, 10.977f, 20.039f)
            curveTo(10.871f, 19.27f, 10.505f, 18.926f, 9.816f, 18.906f)
            curveTo(9.109f, 18.886f, 8.549f, 19.317f, 8.401f, 19.996f)
            curveTo(8.389f, 20.049f, 8.373f, 20.1f, 8.356f, 20.161f)
            horizontalLineTo(8.358f)
            close()
            moveTo(2.397f, 15.717f)
            curveTo(2.397f, 15.717f, 5.637f, 14.142f, 8.887f, 14.142f)
            lineTo(11.338f, 6.577f)
            curveTo(11.43f, 6.211f, 11.698f, 5.963f, 12f, 5.963f)
            curveTo(12.302f, 5.963f, 12.57f, 6.211f, 12.662f, 6.577f)
            lineTo(15.112f, 14.142f)
            curveTo(18.962f, 14.142f, 21.603f, 15.717f, 21.603f, 15.717f)
            lineTo(16.088f, 0.727f)
            curveTo(15.93f, 0.285f, 15.663f, 0f, 15.303f, 0f)
            horizontalLineTo(8.697f)
            curveTo(8.337f, 0f, 8.082f, 0.285f, 7.913f, 0.727f)
            lineTo(2.397f, 15.717f)
            close()
            }
        }.build().also { _astro = it }
    }
