// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.brands

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.BrandIcons

private var _daisyui: ImageVector? = null

/** DaisyUI brand mark (Simple Icons). */
public val BrandIcons.Daisyui: ImageVector
    get() {
        _daisyui?.let { return it }
        return ImageVector.Builder(
            name = "Brand.Daisyui",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(
                fill = SolidColor(Color(0xFF1AD1A5)),
                stroke = null,
            ) {
            moveTo(12f, 0f)
            curveTo(7.828f, 0.001f, 4.396f, 3.433f, 4.395f, 7.605f)
            curveTo(4.396f, 11.777f, 7.828f, 15.209f, 12f, 15.21f)
            curveTo(16.172f, 15.209f, 19.604f, 11.777f, 19.605f, 7.605f)
            curveTo(19.604f, 3.433f, 16.172f, 0.001f, 12f, 0f)
            close()
            moveTo(12f, 0.286f)
            curveTo(16.016f, 0.286f, 19.32f, 3.59f, 19.32f, 7.606f)
            curveTo(19.319f, 11.621f, 16.015f, 14.924f, 12f, 14.924f)
            curveTo(7.985f, 14.924f, 4.681f, 11.62f, 4.68f, 7.605f)
            curveTo(4.68f, 3.589f, 7.984f, 0.285f, 12f, 0.285f)
            close()
            moveTo(12f, 4.326f)
            arcTo(horizontalEllipseRadius = 3.294f, verticalEllipseRadius = 3.294f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 8.721f, y1 = 7.605f)
            verticalLineTo(7.606f)
            arcTo(horizontalEllipseRadius = 3.296f, verticalEllipseRadius = 3.296f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 12f, y1 = 10.884f)
            arcTo(horizontalEllipseRadius = 3.294f, verticalEllipseRadius = 3.294f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 15.279f, y1 = 7.605f)
            arcTo(horizontalEllipseRadius = 3.294f, verticalEllipseRadius = 3.294f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 12f, y1 = 4.326f)
            close()
            moveTo(8.34f, 16.681f)
            horizontalLineTo(8.332f)
            arcTo(horizontalEllipseRadius = 3.67f, verticalEllipseRadius = 3.67f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 4.68f, y1 = 20.333f)
            verticalLineTo(20.348f)
            arcTo(horizontalEllipseRadius = 3.67f, verticalEllipseRadius = 3.67f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 8.332f, y1 = 24f)
            horizontalLineTo(15.668f)
            arcTo(horizontalEllipseRadius = 3.67f, verticalEllipseRadius = 3.67f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 19.32f, y1 = 20.348f)
            verticalLineTo(20.332f)
            arcTo(horizontalEllipseRadius = 3.67f, verticalEllipseRadius = 3.67f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 15.668f, y1 = 16.68f)
            horizontalLineTo(15.66f)
            close()
            }
        }.build().also { _daisyui = it }
    }
