// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.brands

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.BrandIcons

private var _eleventy: ImageVector? = null

/** Eleventy brand mark (Simple Icons). */
public val BrandIcons.Eleventy: ImageVector
    get() {
        _eleventy?.let { return it }
        return ImageVector.Builder(
            name = "Brand.Eleventy",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(
                fill = SolidColor(Color(0xFF222222)),
                stroke = null,
            ) {
            moveTo(3.398f, 12f)
            verticalLineTo(0f)
            horizontalLineTo(20.602f)
            verticalLineTo(24f)
            horizontalLineTo(3.398f)
            close()
            moveTo(16.568f, 18.07f)
            arcTo(horizontalEllipseRadius = 1.07f, verticalEllipseRadius = 1.07f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 16.941f, y1 = 17.963f)
            curveTo(17.373f, 17.75f, 17.621f, 17.291f, 17.818f, 16.337f)
            curveTo(17.894f, 15.965f, 19.013f, 10.169f, 19.027f, 10.074f)
            curveTo(19.053f, 9.888f, 19.019f, 9.692f, 18.943f, 9.598f)
            arcTo(horizontalEllipseRadius = 0.325f, verticalEllipseRadius = 0.325f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 18.856f, y1 = 9.534f)
            lineTo(18.796f, 9.503f)
            horizontalLineTo(18.505f)
            curveTo(18.252f, 9.503f, 18.207f, 9.503f, 18.157f, 9.523f)
            curveTo(18.044f, 9.562f, 17.95f, 9.679f, 17.902f, 9.839f)
            curveTo(17.891f, 9.877f, 17.734f, 10.72f, 17.554f, 11.712f)
            lineTo(17.226f, 13.514f)
            lineTo(17.18f, 13.304f)
            curveTo(16.62f, 10.757f, 16.416f, 9.852f, 16.386f, 9.772f)
            arcTo(horizontalEllipseRadius = 0.383f, verticalEllipseRadius = 0.383f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 16.283f, y1 = 9.612f)
            curveTo(16.178f, 9.505f, 16.166f, 9.502f, 15.716f, 9.502f)
            curveTo(15.305f, 9.502f, 15.294f, 9.502f, 15.216f, 9.576f)
            curveTo(15.13f, 9.655f, 15.094f, 9.792f, 15.105f, 9.996f)
            curveTo(15.111f, 10.111f, 15.15f, 10.266f, 15.793f, 12.78f)
            curveTo(16.456f, 15.367f, 16.544f, 15.723f, 16.58f, 15.957f)
            curveTo(16.626f, 16.257f, 16.53f, 16.67f, 16.372f, 16.85f)
            curveTo(16.34f, 16.887f, 16.335f, 16.889f, 16.288f, 16.882f)
            curveTo(16.26f, 16.882f, 16.168f, 16.855f, 16.084f, 16.831f)
            curveTo(15.816f, 16.753f, 15.722f, 16.759f, 15.622f, 16.859f)
            curveTo(15.526f, 16.955f, 15.485f, 17.107f, 15.484f, 17.369f)
            curveTo(15.484f, 17.625f, 15.512f, 17.709f, 15.643f, 17.842f)
            curveTo(15.774f, 17.975f, 15.967f, 18.05f, 16.238f, 18.072f)
            curveTo(16.402f, 18.084f, 16.458f, 18.084f, 16.568f, 18.071f)
            close()
            moveTo(14.672f, 16.358f)
            arcTo(horizontalEllipseRadius = 0.31f, verticalEllipseRadius = 0.31f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 14.832f, y1 = 16.166f)
            curveTo(14.852f, 16.108f, 14.854f, 16.068f, 14.854f, 15.81f)
            curveTo(14.854f, 15.555f, 14.851f, 15.511f, 14.833f, 15.456f)
            curveTo(14.793f, 15.335f, 14.697f, 15.26f, 14.555f, 15.239f)
            curveTo(14.514f, 15.229f, 14.355f, 15.229f, 14.2f, 15.229f)
            curveTo(13.835f, 15.228f, 13.822f, 15.219f, 13.754f, 15.045f)
            curveTo(13.686f, 14.865f, 13.658f, 14.719f, 13.641f, 14.443f)
            arcTo(horizontalEllipseRadius = 85.799f, verticalEllipseRadius = 85.799f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 13.629f, y1 = 12.503f)
            verticalLineTo(10.738f)
            horizontalLineTo(13.979f)
            curveTo(14.433f, 10.738f, 14.486f, 10.728f, 14.581f, 10.625f)
            arcTo(horizontalEllipseRadius = 0.465f, verticalEllipseRadius = 0.465f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 14.683f, y1 = 10.385f)
            arcTo(horizontalEllipseRadius = 3.273f, verticalEllipseRadius = 3.273f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 14.683f, y1 = 9.851f)
            curveTo(14.657f, 9.691f, 14.584f, 9.58f, 14.472f, 9.529f)
            curveTo(14.415f, 9.504f, 14.407f, 9.503f, 14.022f, 9.499f)
            horizontalLineTo(13.63f)
            lineTo(13.627f, 8.279f)
            curveTo(13.624f, 7.189f, 13.622f, 7.052f, 13.606f, 7.001f)
            arcTo(horizontalEllipseRadius = 0.378f, verticalEllipseRadius = 0.378f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 13.405f, y1 = 6.754f)
            curveTo(13.353f, 6.73f, 13.333f, 6.729f, 13.085f, 6.725f)
            curveTo(12.815f, 6.725f, 12.729f, 6.725f, 12.656f, 6.763f)
            curveTo(12.569f, 6.805f, 12.508f, 6.896f, 12.471f, 7.041f)
            curveTo(12.457f, 7.095f, 12.439f, 7.387f, 12.395f, 8.303f)
            lineTo(12.335f, 9.497f)
            curveTo(12.335f, 9.497f, 12.255f, 9.497f, 12.155f, 9.507f)
            curveTo(11.949f, 9.517f, 11.892f, 9.529f, 11.828f, 9.593f)
            curveTo(11.736f, 9.685f, 11.708f, 9.783f, 11.701f, 10.048f)
            curveTo(11.691f, 10.382f, 11.721f, 10.535f, 11.816f, 10.636f)
            curveTo(11.891f, 10.717f, 11.95f, 10.736f, 12.161f, 10.742f)
            lineTo(12.334f, 10.752f)
            verticalLineTo(12.537f)
            curveTo(12.334f, 14.237f, 12.34f, 14.556f, 12.368f, 14.811f)
            curveTo(12.409f, 15.181f, 12.498f, 15.52f, 12.609f, 15.739f)
            curveTo(12.803f, 16.119f, 13.153f, 16.356f, 13.597f, 16.407f)
            horizontalLineTo(14.602f)
            lineTo(14.672f, 16.367f)
            close()
            moveTo(7.225f, 16.358f)
            curveTo(7.323f, 16.305f, 7.385f, 16.204f, 7.425f, 16.026f)
            curveTo(7.441f, 15.949f, 7.443f, 15.625f, 7.443f, 11.508f)
            curveTo(7.443f, 7.324f, 7.442f, 7.068f, 7.423f, 6.998f)
            curveTo(7.373f, 6.804f, 7.233f, 6.708f, 7.045f, 6.738f)
            curveTo(7.01f, 6.748f, 6.701f, 6.822f, 6.359f, 6.913f)
            curveTo(6.016f, 7.003f, 5.675f, 7.093f, 5.601f, 7.111f)
            curveTo(5.431f, 7.154f, 5.387f, 7.173f, 5.32f, 7.237f)
            curveTo(5.215f, 7.335f, 5.198f, 7.422f, 5.198f, 7.843f)
            curveTo(5.198f, 8.259f, 5.214f, 8.343f, 5.318f, 8.447f)
            curveTo(5.412f, 8.542f, 5.507f, 8.547f, 5.774f, 8.477f)
            curveTo(5.877f, 8.451f, 5.967f, 8.429f, 5.974f, 8.429f)
            curveTo(5.984f, 8.429f, 5.988f, 9.213f, 5.991f, 12.192f)
            curveTo(5.994f, 15.628f, 5.996f, 15.962f, 6.012f, 16.032f)
            curveTo(6.06f, 16.234f, 6.125f, 16.328f, 6.248f, 16.372f)
            curveTo(6.282f, 16.385f, 6.381f, 16.388f, 6.735f, 16.386f)
            curveTo(7.17f, 16.386f, 7.18f, 16.386f, 7.225f, 16.359f)
            close()
            moveTo(10.428f, 16.358f)
            curveTo(10.52f, 16.312f, 10.58f, 16.223f, 10.625f, 16.068f)
            lineTo(10.649f, 15.984f)
            lineTo(10.652f, 11.549f)
            curveTo(10.654f, 8.355f, 10.652f, 7.093f, 10.642f, 7.04f)
            curveTo(10.609f, 6.84f, 10.497f, 6.732f, 10.32f, 6.732f)
            curveTo(10.254f, 6.732f, 10.122f, 6.762f, 9.463f, 6.936f)
            curveTo(8.903f, 7.083f, 8.664f, 7.15f, 8.614f, 7.175f)
            arcTo(horizontalEllipseRadius = 0.34f, verticalEllipseRadius = 0.34f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 8.444f, y1 = 7.359f)
            curveTo(8.42f, 7.419f, 8.42f, 7.43f, 8.42f, 7.838f)
            curveTo(8.42f, 8.253f, 8.42f, 8.255f, 8.446f, 8.321f)
            arcTo(horizontalEllipseRadius = 0.362f, verticalEllipseRadius = 0.362f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 8.529f, y1 = 8.441f)
            curveTo(8.629f, 8.541f, 8.701f, 8.546f, 8.985f, 8.475f)
            arcTo(horizontalEllipseRadius = 5.46f, verticalEllipseRadius = 5.46f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 9.193f, y1 = 8.425f)
            curveTo(9.201f, 8.425f, 9.205f, 9.627f, 9.207f, 12.216f)
            lineTo(9.21f, 16.006f)
            lineTo(9.236f, 16.092f)
            arcTo(horizontalEllipseRadius = 0.48f, verticalEllipseRadius = 0.48f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 9.371f, y1 = 16.322f)
            curveTo(9.449f, 16.384f, 9.456f, 16.385f, 9.941f, 16.382f)
            curveTo(10.355f, 16.382f, 10.388f, 16.382f, 10.428f, 16.358f)
            close()
            }
        }.build().also { _eleventy = it }
    }
