// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.brands

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.BrandIcons

private var _html5: ImageVector? = null

/** HTML5 brand mark (Simple Icons). */
public val BrandIcons.Html5: ImageVector
    get() {
        _html5?.let { return it }
        return ImageVector.Builder(
            name = "Brand.Html5",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(
                fill = SolidColor(Color(0xFFE34F26)),
                stroke = null,
            ) {
            moveTo(1.5f, 0f)
            horizontalLineTo(22.5f)
            lineTo(20.59f, 21.563f)
            lineTo(11.977f, 24f)
            lineTo(3.413f, 21.562f)
            lineTo(1.5f, 0f)
            close()
            moveTo(8.531f, 9.75f)
            lineTo(8.299f, 7.032f)
            lineTo(18.358f, 7.035f)
            lineTo(18.588f, 4.413f)
            lineTo(5.412f, 4.41f)
            lineTo(6.11f, 12.42f)
            horizontalLineTo(15.236f)
            lineTo(14.91f, 15.846f)
            lineTo(12f, 16.65f)
            lineTo(9.045f, 15.84f)
            lineTo(8.857f, 13.73f)
            horizontalLineTo(6.248f)
            lineTo(6.578f, 17.901f)
            lineTo(12f, 19.351f)
            lineTo(17.379f, 17.908f)
            lineTo(18.123f, 9.751f)
            horizontalLineTo(8.531f)
            close()
            }
        }.build().also { _html5 = it }
    }
