// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.brands

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.BrandIcons

private var _lit: ImageVector? = null

/** Lit brand mark (Simple Icons). */
public val BrandIcons.Lit: ImageVector
    get() {
        _lit?.let { return it }
        return ImageVector.Builder(
            name = "Brand.Lit",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(
                fill = SolidColor(Color(0xFF324FFF)),
                stroke = null,
            ) {
            moveTo(2.4f, 9.6f)
            lineTo(7.2f, 14.4f)
            verticalLineTo(24f)
            lineTo(2.4f, 19.2f)
            verticalLineTo(9.6f)
            close()
            moveTo(7.2f, 4.8f)
            verticalLineTo(14.4f)
            lineTo(12f, 9.6f)
            verticalLineTo(0f)
            lineTo(7.2f, 4.8f)
            close()
            moveTo(12f, 9.6f)
            verticalLineTo(19.2f)
            lineTo(16.8f, 14.4f)
            verticalLineTo(4.8f)
            lineTo(12f, 9.6f)
            close()
            moveTo(16.8f, 14.4f)
            verticalLineTo(24f)
            lineTo(21.6f, 19.2f)
            verticalLineTo(9.6f)
            lineTo(16.8f, 14.4f)
            close()
            }
        }.build().also { _lit = it }
    }
