// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.brands

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.BrandIcons

private var _lucide: ImageVector? = null

/** Lucide brand mark (Simple Icons). */
public val BrandIcons.Lucide: ImageVector
    get() {
        _lucide?.let { return it }
        return ImageVector.Builder(
            name = "Brand.Lucide",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(
                fill = SolidColor(Color(0xFFF56565)),
                stroke = null,
            ) {
            moveTo(18.483f, 1.123f)
            arcTo(horizontalEllipseRadius = 1.09f, verticalEllipseRadius = 1.09f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 17.731f, y1 = 1.485f)
            arcTo(horizontalEllipseRadius = 1.09f, verticalEllipseRadius = 1.09f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 17.819f, y1 = 3.025f)
            arcTo(horizontalEllipseRadius = 11.956f, verticalEllipseRadius = 11.956f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 21.819f, y1 = 11.971f)
            arcTo(horizontalEllipseRadius = 7.62f, verticalEllipseRadius = 7.62f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 14.182f, y1 = 19.607f)
            arcTo(horizontalEllipseRadius = 7.62f, verticalEllipseRadius = 7.62f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 6.545f, y1 = 11.971f)
            arcTo(horizontalEllipseRadius = 3.255f, verticalEllipseRadius = 3.255f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 9.818f, y1 = 8.698f)
            curveTo(11.638f, 8.698f, 13.091f, 10.148f, 13.091f, 11.971f)
            arcTo(horizontalEllipseRadius = 1.09f, verticalEllipseRadius = 1.09f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 14.181f, y1 = 13.061f)
            arcTo(horizontalEllipseRadius = 1.09f, verticalEllipseRadius = 1.09f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 15.273f, y1 = 11.971f)
            curveTo(15.273f, 8.971f, 12.818f, 6.516f, 9.818f, 6.516f)
            curveTo(6.818f, 6.516f, 4.364f, 8.971f, 4.364f, 11.971f)
            curveTo(4.364f, 17.379f, 8.772f, 21.789f, 14.182f, 21.789f)
            curveTo(19.592f, 21.789f, 24f, 17.379f, 24f, 11.971f)
            arcTo(horizontalEllipseRadius = 14.16f, verticalEllipseRadius = 14.16f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 19.272f, y1 = 1.4f)
            arcTo(horizontalEllipseRadius = 1.09f, verticalEllipseRadius = 1.09f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 18.483f, y1 = 1.123f)
            close()
            moveTo(9.818f, 2.15f)
            curveTo(4.408f, 2.151f, 0f, 6.561f, 0f, 11.97f)
            arcTo(horizontalEllipseRadius = 14.16f, verticalEllipseRadius = 14.16f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 4.8f, y1 = 22.607f)
            arcTo(horizontalEllipseRadius = 1.09f, verticalEllipseRadius = 1.09f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 6.34f, y1 = 22.511f)
            arcTo(horizontalEllipseRadius = 1.09f, verticalEllipseRadius = 1.09f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 6.245f, y1 = 20.971f)
            arcTo(horizontalEllipseRadius = 11.957f, verticalEllipseRadius = 11.957f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 2.182f, y1 = 11.971f)
            arcTo(horizontalEllipseRadius = 7.62f, verticalEllipseRadius = 7.62f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 9.818f, y1 = 4.334f)
            arcTo(horizontalEllipseRadius = 7.62f, verticalEllipseRadius = 7.62f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 17.455f, y1 = 11.97f)
            arcTo(horizontalEllipseRadius = 3.256f, verticalEllipseRadius = 3.256f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 14.182f, y1 = 15.243f)
            arcTo(horizontalEllipseRadius = 3.256f, verticalEllipseRadius = 3.256f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 10.909f, y1 = 11.97f)
            arcTo(horizontalEllipseRadius = 1.09f, verticalEllipseRadius = 1.09f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 9.819f, y1 = 10.88f)
            arcTo(horizontalEllipseRadius = 1.09f, verticalEllipseRadius = 1.09f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 8.727f, y1 = 11.97f)
            curveTo(8.727f, 14.97f, 11.182f, 17.425f, 14.182f, 17.425f)
            curveTo(17.182f, 17.425f, 19.636f, 14.97f, 19.636f, 11.97f)
            curveTo(19.636f, 6.562f, 15.228f, 2.152f, 9.818f, 2.152f)
            close()
            }
        }.build().also { _lucide = it }
    }
