// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.brands

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.BrandIcons

private var _nextjs: ImageVector? = null

/** Next.js brand mark (Simple Icons). */
public val BrandIcons.Nextjs: ImageVector
    get() {
        _nextjs?.let { return it }
        return ImageVector.Builder(
            name = "Brand.Nextjs",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000)),
                stroke = null,
            ) {
            moveTo(18.665f, 21.978f)
            curveTo(16.758f, 23.255f, 14.465f, 24f, 12f, 24f)
            curveTo(5.377f, 24f, 0f, 18.623f, 0f, 12f)
            curveTo(0f, 5.377f, 5.377f, 0f, 12f, 0f)
            curveTo(18.623f, 0f, 24f, 5.377f, 24f, 12f)
            curveTo(24f, 15.583f, 22.426f, 18.801f, 19.933f, 21.001f)
            lineTo(9.219f, 7.2f)
            horizontalLineTo(7.2f)
            verticalLineTo(16.796f)
            horizontalLineTo(8.815f)
            verticalLineTo(9.251f)
            lineTo(18.665f, 21.978f)
            close()
            moveTo(15.333f, 13.445f)
            lineTo(16.933f, 15.506f)
            verticalLineTo(7.2f)
            horizontalLineTo(15.333f)
            verticalLineTo(13.445f)
            close()
            }
        }.build().also { _nextjs = it }
    }
