// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.brands

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.BrandIcons

private var _nuxt: ImageVector? = null

/** Nuxt brand mark (Simple Icons). */
public val BrandIcons.Nuxt: ImageVector
    get() {
        _nuxt?.let { return it }
        return ImageVector.Builder(
            name = "Brand.Nuxt",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(
                fill = SolidColor(Color(0xFF00DC82)),
                stroke = null,
            ) {
            moveTo(13.4642f, 19.8295f)
            horizontalLineTo(22.386f)
            curveTo(22.6694f, 19.8295f, 22.9478f, 19.7572f, 23.1932f, 19.6197f)
            arcTo(horizontalEllipseRadius = 1.5899f, verticalEllipseRadius = 1.5899f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 23.784f, y1 = 19.0465f)
            arcTo(horizontalEllipseRadius = 1.5293f, verticalEllipseRadius = 1.5293f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 24f, y1 = 18.2635f)
            arcTo(horizontalEllipseRadius = 1.529f, verticalEllipseRadius = 1.529f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 23.7833f, y1 = 17.4807f)
            lineTo(17.7916f, 7.4142f)
            arcTo(horizontalEllipseRadius = 1.5904f, verticalEllipseRadius = 1.5904f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 17.2009f, y1 = 6.8412f)
            arcTo(horizontalEllipseRadius = 1.6524f, verticalEllipseRadius = 1.6524f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 16.3939f, y1 = 6.6313f)
            curveTo(16.1106f, 6.6313f, 15.8323f, 6.7037f, 15.5869f, 6.8411f)
            arcTo(horizontalEllipseRadius = 1.5904f, verticalEllipseRadius = 1.5904f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 14.9962f, y1 = 7.4142f)
            lineTo(13.4642f, 9.99f)
            lineTo(10.4688f, 4.9534f)
            arcTo(horizontalEllipseRadius = 1.5913f, verticalEllipseRadius = 1.5913f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 9.8778f, y1 = 4.3804f)
            arcTo(horizontalEllipseRadius = 1.6533f, verticalEllipseRadius = 1.6533f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 9.0707f, y1 = 4.1706f)
            curveTo(8.7873f, 4.1706f, 8.509f, 4.2429f, 8.2635f, 4.3803f)
            arcTo(horizontalEllipseRadius = 1.5913f, verticalEllipseRadius = 1.5913f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 7.6725f, y1 = 4.9533f)
            lineTo(0.2168f, 17.4808f)
            arcTo(horizontalEllipseRadius = 1.5292f, verticalEllipseRadius = 1.5292f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 0f, y1 = 18.2635f)
            curveTo(-0.0001f, 18.5384f, 0.0744f, 18.8085f, 0.216f, 19.0465f)
            arcTo(horizontalEllipseRadius = 1.59f, verticalEllipseRadius = 1.59f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 0.8068f, y1 = 19.6197f)
            curveTo(1.0522f, 19.7572f, 1.3306f, 19.8295f, 1.614f, 19.8295f)
            horizontalLineTo(7.2143f)
            curveTo(9.4333f, 19.8295f, 11.0697f, 18.8841f, 12.1956f, 17.0396f)
            lineTo(14.9293f, 12.4474f)
            lineTo(16.3935f, 9.99f)
            lineTo(20.7879f, 17.372f)
            horizontalLineTo(14.9293f)
            close()
            moveTo(7.123f, 17.3694f)
            lineTo(3.2147f, 17.3685f)
            lineTo(9.0733f, 7.5264f)
            lineTo(11.9965f, 12.4474f)
            lineTo(10.0393f, 15.7366f)
            curveTo(9.2915f, 16.9333f, 8.4421f, 17.3694f, 7.123f, 17.3694f)
            close()
            }
        }.build().also { _nuxt = it }
    }
