// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.brands

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.BrandIcons

private var _qwik: ImageVector? = null

/** Qwik brand mark (Simple Icons). */
public val BrandIcons.Qwik: ImageVector
    get() {
        _qwik?.let { return it }
        return ImageVector.Builder(
            name = "Brand.Qwik",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(
                fill = SolidColor(Color(0xFFAC7EF4)),
                stroke = null,
            ) {
            moveTo(7.5469f, 0f)
            arcTo(horizontalEllipseRadius = 2.957f, verticalEllipseRadius = 2.957f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 4.9863f, y1 = 1.4785f)
            lineTo(0.5332f, 9.1915f)
            arcTo(horizontalEllipseRadius = 2.957f, verticalEllipseRadius = 2.957f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 0.5332f, y1 = 12.1485f)
            lineTo(4.9863f, 19.8613f)
            arcTo(horizontalEllipseRadius = 2.955f, verticalEllipseRadius = 2.955f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 7.547f, y1 = 21.338f)
            horizontalLineTo(12f)
            lineTo(20.5938f, 23.9864f)
            curveTo(20.8347f, 24.0606f, 21.045f, 23.8082f, 20.9297f, 23.5841f)
            lineTo(19.0137f, 19.8614f)
            lineTo(23.4668f, 12.1485f)
            arcTo(horizontalEllipseRadius = 2.957f, verticalEllipseRadius = 2.957f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 23.4668f, y1 = 9.1915f)
            lineTo(19.0137f, 1.4786f)
            arcTo(horizontalEllipseRadius = 2.957f, verticalEllipseRadius = 2.957f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 16.453f, y1 = 0f)
            close()
            moveTo(7.5469f, 0.7656f)
            lineTo(17.7324f, 10.67f)
            lineTo(15.8359f, 12.5685f)
            lineTo(16.4141f, 20.1017f)
            lineTo(6.2676f, 10.67f)
            lineTo(8.6386f, 8.297f)
            close()
            }
        }.build().also { _qwik = it }
    }
