// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.brands

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.BrandIcons

private var _reactBrand: ImageVector? = null

/** React brand mark (Simple Icons). */
public val BrandIcons.ReactBrand: ImageVector
    get() {
        _reactBrand?.let { return it }
        return ImageVector.Builder(
            name = "Brand.ReactBrand",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(
                fill = SolidColor(Color(0xFF61DAFB)),
                stroke = null,
            ) {
            moveTo(14.23f, 12.004f)
            arcTo(horizontalEllipseRadius = 2.236f, verticalEllipseRadius = 2.236f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 11.995f, y1 = 14.24f)
            arcTo(horizontalEllipseRadius = 2.236f, verticalEllipseRadius = 2.236f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 9.759f, y1 = 12.004f)
            arcTo(horizontalEllipseRadius = 2.236f, verticalEllipseRadius = 2.236f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 11.994f, y1 = 9.768f)
            arcTo(horizontalEllipseRadius = 2.236f, verticalEllipseRadius = 2.236f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 14.23f, y1 = 12.004f)
            close()
            moveTo(16.878f, 1.314f)
            curveTo(15.532f, 1.314f, 13.771f, 2.274f, 11.99f, 3.936f)
            curveTo(10.21f, 2.283f, 8.448f, 1.334f, 7.103f, 1.334f)
            curveTo(6.693f, 1.334f, 6.32f, 1.427f, 5.997f, 1.612f)
            curveTo(4.622f, 2.405f, 4.314f, 4.876f, 5.024f, 7.977f)
            curveTo(1.98f, 8.917f, 0f, 10.42f, 0f, 12.004f)
            curveTo(0f, 13.594f, 1.99f, 15.101f, 5.043f, 16.034f)
            curveTo(4.339f, 19.147f, 4.653f, 21.622f, 6.031f, 22.414f)
            curveTo(6.351f, 22.601f, 6.721f, 22.689f, 7.133f, 22.689f)
            curveTo(8.478f, 22.689f, 10.24f, 21.729f, 12.021f, 20.065f)
            curveTo(13.801f, 21.719f, 15.563f, 22.668f, 16.908f, 22.668f)
            curveTo(17.318f, 22.668f, 17.691f, 22.578f, 18.014f, 22.393f)
            curveTo(19.388f, 21.601f, 19.697f, 19.13f, 18.987f, 16.028f)
            curveTo(22.02f, 15.096f, 24f, 13.59f, 24f, 12.004f)
            curveTo(24f, 10.414f, 22.01f, 8.907f, 18.957f, 7.972f)
            curveTo(19.661f, 4.862f, 19.347f, 2.385f, 17.969f, 1.592f)
            curveTo(17.651f, 1.408f, 17.281f, 1.315f, 16.877f, 1.314f)
            close()
            moveTo(16.873f, 2.404f)
            verticalLineTo(2.41f)
            curveTo(17.098f, 2.41f, 17.279f, 2.454f, 17.431f, 2.537f)
            curveTo(18.097f, 2.919f, 18.386f, 4.372f, 18.161f, 6.241f)
            curveTo(18.107f, 6.701f, 18.019f, 7.186f, 17.911f, 7.681f)
            curveTo(16.951f, 7.445f, 15.905f, 7.264f, 14.804f, 7.147f)
            curveTo(14.144f, 6.242f, 13.459f, 5.42f, 12.769f, 4.7f)
            curveTo(14.361f, 3.22f, 15.856f, 2.408f, 16.874f, 2.405f)
            close()
            moveTo(7.103f, 2.424f)
            curveTo(8.115f, 2.424f, 9.617f, 3.232f, 11.213f, 4.704f)
            curveTo(10.527f, 5.424f, 9.843f, 6.241f, 9.193f, 7.146f)
            curveTo(8.086f, 7.263f, 7.039f, 7.444f, 6.08f, 7.684f)
            curveTo(5.968f, 7.194f, 5.885f, 6.72f, 5.826f, 6.264f)
            curveTo(5.596f, 4.396f, 5.88f, 2.944f, 6.54f, 2.557f)
            curveTo(6.73f, 2.467f, 6.94f, 2.43f, 7.103f, 2.425f)
            close()
            moveTo(11.985f, 5.474f)
            curveTo(12.44f, 5.942f, 12.895f, 6.466f, 13.345f, 7.038f)
            curveTo(12.905f, 7.018f, 12.455f, 7.004f, 12f, 7.004f)
            curveTo(11.54f, 7.004f, 11.085f, 7.014f, 10.64f, 7.038f)
            curveTo(11.08f, 6.466f, 11.535f, 5.942f, 11.985f, 5.473f)
            close()
            moveTo(12f, 8.1f)
            curveTo(12.74f, 8.1f, 13.477f, 8.134f, 14.202f, 8.193f)
            curveTo(14.608f, 8.775f, 15.004f, 9.396f, 15.385f, 10.053f)
            curveTo(15.757f, 10.693f, 16.095f, 11.343f, 16.403f, 11.999f)
            curveTo(16.095f, 12.654f, 15.757f, 13.309f, 15.39f, 13.949f)
            curveTo(15.01f, 14.609f, 14.617f, 15.237f, 14.21f, 15.819f)
            curveTo(13.482f, 15.882f, 12.744f, 15.917f, 12f, 15.917f)
            curveTo(11.26f, 15.917f, 10.523f, 15.882f, 9.798f, 15.824f)
            curveTo(9.392f, 15.242f, 8.996f, 14.62f, 8.615f, 13.964f)
            curveTo(8.243f, 13.324f, 7.905f, 12.674f, 7.597f, 12.018f)
            curveTo(7.9f, 11.361f, 8.243f, 10.705f, 8.61f, 10.064f)
            curveTo(8.99f, 9.404f, 9.383f, 8.778f, 9.79f, 8.196f)
            curveTo(10.518f, 8.132f, 11.256f, 8.098f, 12f, 8.098f)
            close()
            moveTo(8.365f, 8.354f)
            curveTo(8.125f, 8.731f, 7.885f, 9.117f, 7.661f, 9.514f)
            curveTo(7.436f, 9.904f, 7.226f, 10.296f, 7.026f, 10.688f)
            curveTo(6.761f, 10.032f, 6.536f, 9.378f, 6.35f, 8.741f)
            curveTo(6.99f, 8.591f, 7.665f, 8.458f, 8.365f, 8.355f)
            close()
            moveTo(15.625f, 8.354f)
            curveTo(16.32f, 8.457f, 16.99f, 8.584f, 17.631f, 8.741f)
            curveTo(17.451f, 9.373f, 17.226f, 10.023f, 16.971f, 10.674f)
            curveTo(16.771f, 10.284f, 16.561f, 9.891f, 16.331f, 9.5f)
            curveTo(16.106f, 9.108f, 15.866f, 8.726f, 15.626f, 8.354f)
            close()
            moveTo(18.688f, 9.029f)
            curveTo(19.172f, 9.179f, 19.632f, 9.346f, 20.063f, 9.527f)
            curveTo(21.795f, 10.267f, 22.915f, 11.235f, 22.915f, 12.003f)
            curveTo(22.91f, 12.771f, 21.79f, 13.743f, 20.058f, 14.478f)
            curveTo(19.638f, 14.658f, 19.178f, 14.82f, 18.703f, 14.971f)
            curveTo(18.423f, 14.013f, 18.057f, 13.015f, 17.603f, 11.991f)
            curveTo(18.053f, 10.974f, 18.413f, 9.981f, 18.688f, 9.027f)
            close()
            moveTo(5.293f, 9.033f)
            curveTo(5.571f, 9.993f, 5.938f, 10.99f, 6.393f, 12.013f)
            curveTo(5.943f, 13.03f, 5.581f, 14.023f, 5.307f, 14.977f)
            curveTo(4.823f, 14.827f, 4.363f, 14.659f, 3.937f, 14.477f)
            curveTo(2.205f, 13.74f, 1.085f, 12.771f, 1.085f, 12.003f)
            curveTo(1.085f, 11.235f, 2.205f, 10.261f, 3.937f, 9.527f)
            curveTo(4.357f, 9.347f, 4.817f, 9.185f, 5.293f, 9.033f)
            close()
            moveTo(16.971f, 13.313f)
            curveTo(17.236f, 13.97f, 17.461f, 14.625f, 17.647f, 15.261f)
            curveTo(17.007f, 15.418f, 16.331f, 15.551f, 15.631f, 15.651f)
            curveTo(15.871f, 15.276f, 16.111f, 14.889f, 16.336f, 14.493f)
            curveTo(16.561f, 14.103f, 16.771f, 13.705f, 16.972f, 13.313f)
            close()
            moveTo(7.026f, 13.333f)
            curveTo(7.226f, 13.725f, 7.436f, 14.116f, 7.666f, 14.508f)
            curveTo(7.896f, 14.898f, 8.131f, 15.28f, 8.371f, 15.651f)
            curveTo(7.676f, 15.549f, 7.006f, 15.421f, 6.365f, 15.265f)
            curveTo(6.545f, 14.635f, 6.771f, 13.983f, 7.025f, 13.332f)
            close()
            moveTo(17.92f, 16.32f)
            curveTo(18.032f, 16.813f, 18.12f, 17.288f, 18.174f, 17.743f)
            curveTo(18.404f, 19.611f, 18.12f, 21.063f, 17.46f, 21.451f)
            curveTo(17.313f, 21.541f, 17.122f, 21.579f, 16.897f, 21.579f)
            curveTo(15.885f, 21.579f, 14.383f, 20.772f, 12.787f, 19.299f)
            curveTo(13.473f, 18.579f, 14.157f, 17.763f, 14.807f, 16.859f)
            curveTo(15.914f, 16.741f, 16.961f, 16.559f, 17.92f, 16.319f)
            close()
            moveTo(6.09f, 16.33f)
            curveTo(7.05f, 16.564f, 8.096f, 16.745f, 9.197f, 16.862f)
            curveTo(9.857f, 17.767f, 10.542f, 18.589f, 11.232f, 19.308f)
            curveTo(9.637f, 20.791f, 8.14f, 21.603f, 7.122f, 21.603f)
            curveTo(6.902f, 21.598f, 6.716f, 21.553f, 6.569f, 21.471f)
            curveTo(5.903f, 21.091f, 5.614f, 19.637f, 5.839f, 17.768f)
            curveTo(5.893f, 17.308f, 5.981f, 16.824f, 6.089f, 16.33f)
            close()
            moveTo(10.65f, 16.97f)
            curveTo(11.09f, 16.99f, 11.54f, 17.004f, 11.995f, 17.004f)
            curveTo(12.455f, 17.004f, 12.91f, 16.994f, 13.355f, 16.97f)
            curveTo(12.915f, 17.542f, 12.46f, 18.065f, 12.01f, 18.535f)
            curveTo(11.555f, 18.065f, 11.1f, 17.542f, 10.65f, 16.97f)
            close()
            }
        }.build().also { _reactBrand = it }
    }
