// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.brands

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.BrandIcons

private var _remix: ImageVector? = null

/** Remix brand mark (Simple Icons). */
public val BrandIcons.Remix: ImageVector
    get() {
        _remix?.let { return it }
        return ImageVector.Builder(
            name = "Brand.Remix",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000)),
                stroke = null,
            ) {
            moveTo(21.511f, 18.508f)
            curveTo(21.727f, 21.281f, 21.727f, 22.581f, 21.727f, 24f)
            horizontalLineTo(15.31f)
            curveTo(15.31f, 23.691f, 15.316f, 23.408f, 15.321f, 23.122f)
            curveTo(15.339f, 22.23f, 15.357f, 21.301f, 15.212f, 19.424f)
            curveTo(15.022f, 16.677f, 13.838f, 16.066f, 11.662f, 16.066f)
            horizontalLineTo(1.574f)
            verticalLineTo(11.066f)
            horizontalLineTo(11.97f)
            curveTo(14.718f, 11.066f, 16.092f, 10.231f, 16.092f, 8.017f)
            curveTo(16.092f, 6.071f, 14.718f, 4.892f, 11.97f, 4.892f)
            horizontalLineTo(1.573f)
            verticalLineTo(0f)
            horizontalLineTo(13.114f)
            curveTo(19.335f, 0f, 22.427f, 2.938f, 22.427f, 7.632f)
            curveTo(22.427f, 11.143f, 20.251f, 13.432f, 17.313f, 13.814f)
            curveTo(19.793f, 14.311f, 21.243f, 15.723f, 21.511f, 18.508f)
            close()
            moveTo(1.573f, 24f)
            verticalLineTo(20.273f)
            horizontalLineTo(8.357f)
            curveTo(9.49f, 20.273f, 9.736f, 21.113f, 9.736f, 21.615f)
            verticalLineTo(24f)
            close()
            }
        }.build().also { _remix = it }
    }
