// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.brands

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.BrandIcons

private var _simpleIcons: ImageVector? = null

/** Simple Icons brand mark (Simple Icons). */
public val BrandIcons.SimpleIcons: ImageVector
    get() {
        _simpleIcons?.let { return it }
        return ImageVector.Builder(
            name = "Brand.SimpleIcons",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(
                fill = SolidColor(Color(0xFF111111)),
                stroke = null,
            ) {
            moveTo(12f, 0f)
            curveTo(8.688f, 0f, 6f, 2.688f, 6f, 6f)
            curveTo(6f, 9.312f, 8.688f, 12f, 12f, 12f)
            curveTo(16.64f, 11.999f, 19.526f, 17.039f, 17.176f, 21.04f)
            horizontalLineTo(18.856f)
            arcTo(horizontalEllipseRadius = 7.507f, verticalEllipseRadius = 7.507f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 12f, y1 = 10.5f)
            arcTo(horizontalEllipseRadius = 4.502f, verticalEllipseRadius = 4.502f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 7.5f, y1 = 6f)
            curveTo(7.5f, 3.516f, 9.516f, 1.5f, 12f, 1.5f)
            curveTo(14.484f, 1.5f, 16.5f, 3.516f, 16.5f, 6f)
            horizontalLineTo(18f)
            curveTo(18f, 2.688f, 15.312f, 0f, 12f, 0f)
            close()
            moveTo(12f, 3f)
            arcTo(horizontalEllipseRadius = 3f, verticalEllipseRadius = 3f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 12f, y1 = 9f)
            curveTo(16f, 9f, 16f, 3f, 12f, 3f)
            close()
            moveTo(12f, 4.5f)
            arcTo(horizontalEllipseRadius = 1.5f, verticalEllipseRadius = 1.5f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 13.5f, y1 = 6f)
            verticalLineTo(6.002f)
            curveTo(13.498f, 7.338f, 11.883f, 8.005f, 10.939f, 7.06f)
            curveTo(9.995f, 6.115f, 10.664f, 4.5f, 12f, 4.5f)
            close()
            moveTo(7.5f, 15f)
            verticalLineTo(16.5f)
            horizontalLineTo(9f)
            verticalLineTo(22.5f)
            horizontalLineTo(4.5f)
            verticalLineTo(24f)
            horizontalLineTo(19.5f)
            verticalLineTo(22.5f)
            horizontalLineTo(15f)
            verticalLineTo(16.5f)
            horizontalLineTo(16.5f)
            verticalLineTo(15f)
            close()
            moveTo(10.5f, 16.5f)
            horizontalLineTo(13.5f)
            verticalLineTo(22.5f)
            horizontalLineTo(10.5f)
            close()
            moveTo(4.5f, 17.97f)
            curveTo(4.5f, 19.06f, 4.716f, 20.079f, 5.144f, 21.039f)
            horizontalLineTo(6.828f)
            arcTo(horizontalEllipseRadius = 5.957f, verticalEllipseRadius = 5.957f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 6f, y1 = 17.97f)
            close()
            }
        }.build().also { _simpleIcons = it }
    }
