// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.brands

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.BrandIcons

private var _solid: ImageVector? = null

/** Solid brand mark (Simple Icons). */
public val BrandIcons.Solid: ImageVector
    get() {
        _solid?.let { return it }
        return ImageVector.Builder(
            name = "Brand.Solid",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(
                fill = SolidColor(Color(0xFF2C4F7C)),
                stroke = null,
            ) {
            moveTo(11.558f, 0.788f)
            arcTo(horizontalEllipseRadius = 9.082f, verticalEllipseRadius = 9.082f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 9.776f, y1 = 0.99f)
            lineTo(9.323f, 1.14f)
            curveTo(8.417f, 1.443f, 7.667f, 1.895f, 7.223f, 2.488f)
            lineTo(6.922f, 2.94f)
            lineTo(4.887f, 6.468f)
            curveTo(5.313f, 6.081f, 5.861f, 5.77f, 6.53f, 5.574f)
            horizontalLineTo(6.531f)
            lineTo(7.144f, 5.42f)
            horizontalLineTo(7.145f)
            arcTo(horizontalEllipseRadius = 8.82f, verticalEllipseRadius = 8.82f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 8.922f, y1 = 5.214f)
            curveTo(11.838f, 5.161f, 14.955f, 6.362f, 17.345f, 7.574f)
            curveTo(19.662f, 8.749f, 21.233f, 9.894f, 21.332f, 9.964f)
            lineTo(24f, 5.518f)
            curveTo(23.918f, 5.458f, 22.34f, 4.308f, 20.009f, 3.132f)
            curveTo(17.616f, 1.926f, 14.488f, 0.736f, 11.559f, 0.789f)
            close()
            moveTo(8.924f, 5.366f)
            arcTo(horizontalEllipseRadius = 8.634f, verticalEllipseRadius = 8.634f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 7.179f, y1 = 5.569f)
            lineTo(6.573f, 5.72f)
            curveTo(5.295f, 6.096f, 4.478f, 6.88f, 4.143f, 7.828f)
            curveTo(3.809f, 8.776f, 3.955f, 9.893f, 4.63f, 10.944f)
            curveTo(4.96f, 11.374f, 5.377f, 11.757f, 5.846f, 12.091f)
            lineTo(12.328f, 10f)
            horizontalLineTo(12.329f)
            arcTo(horizontalEllipseRadius = 6.943f, verticalEllipseRadius = 6.943f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 18.342f, y1 = 11.013f)
            lineTo(21.186f, 10.05f)
            curveTo(21.016f, 9.926f, 19.523f, 8.85f, 17.276f, 7.71f)
            curveTo(14.897f, 6.504f, 11.797f, 5.314f, 8.924f, 5.366f)
            close()
            moveTo(14.359f, 9.863f)
            arcTo(horizontalEllipseRadius = 6.791f, verticalEllipseRadius = 6.791f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 12.375f, y1 = 10.146f)
            lineTo(2.94f, 13.189f)
            lineTo(0f, 18.334f)
            lineTo(9.276f, 15.342f)
            arcTo(horizontalEllipseRadius = 6.945f, verticalEllipseRadius = 6.945f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 16.684f, y1 = 17.656f)
            verticalLineTo(17.657f)
            curveTo(17.379f, 18.56f, 17.574f, 19.563f, 17.344f, 20.465f)
            lineTo(19.916f, 15.835f)
            curveTo(20.511f, 14.794f, 20.366f, 13.61f, 19.614f, 12.406f)
            arcTo(horizontalEllipseRadius = 6.792f, verticalEllipseRadius = 6.792f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 14.359f, y1 = 9.863f)
            close()
            moveTo(11.328f, 15.204f)
            arcTo(horizontalEllipseRadius = 6.787f, verticalEllipseRadius = 6.787f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 9.322f, y1 = 15.487f)
            lineTo(0.008f, 18.492f)
            curveTo(0.183f, 18.623f, 2.028f, 19.99f, 4.695f, 21.26f)
            curveTo(7.492f, 22.592f, 11.065f, 23.727f, 14.163f, 22.972f)
            lineTo(14.617f, 22.82f)
            horizontalLineTo(14.619f)
            curveTo(15.897f, 22.444f, 16.753f, 21.658f, 17.106f, 20.73f)
            curveTo(17.459f, 19.8f, 17.313f, 18.726f, 16.565f, 17.752f)
            arcTo(horizontalEllipseRadius = 6.791f, verticalEllipseRadius = 6.791f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 11.328f, y1 = 15.204f)
            close()
            }
        }.build().also { _solid = it }
    }
