// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.brands

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.BrandIcons

private var _svelte: ImageVector? = null

/** Svelte brand mark (Simple Icons). */
public val BrandIcons.Svelte: ImageVector
    get() {
        _svelte?.let { return it }
        return ImageVector.Builder(
            name = "Brand.Svelte",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(
                fill = SolidColor(Color(0xFFFF3E00)),
                stroke = null,
            ) {
            moveTo(10.354f, 21.125f)
            arcTo(horizontalEllipseRadius = 4.44f, verticalEllipseRadius = 4.44f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 5.589f, y1 = 19.358f)
            arcTo(horizontalEllipseRadius = 4.109f, verticalEllipseRadius = 4.109f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 4.886f, y1 = 16.251f)
            arcTo(horizontalEllipseRadius = 3.898f, verticalEllipseRadius = 3.898f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 5.02f, y1 = 15.729f)
            lineTo(5.125f, 15.408f)
            lineTo(5.412f, 15.618f)
            arcTo(horizontalEllipseRadius = 7.21f, verticalEllipseRadius = 7.21f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 7.598f, y1 = 16.71f)
            lineTo(7.806f, 16.773f)
            lineTo(7.786f, 16.981f)
            arcTo(horizontalEllipseRadius = 1.253f, verticalEllipseRadius = 1.253f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 8.012f, y1 = 17.811f)
            arcTo(horizontalEllipseRadius = 1.337f, verticalEllipseRadius = 1.337f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 9.447f, y1 = 18.344f)
            arcTo(horizontalEllipseRadius = 1.231f, verticalEllipseRadius = 1.231f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 9.79f, y1 = 18.194f)
            lineTo(15.38f, 14.632f)
            arcTo(horizontalEllipseRadius = 1.164f, verticalEllipseRadius = 1.164f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 15.904f, y1 = 13.854f)
            arcTo(horizontalEllipseRadius = 1.242f, verticalEllipseRadius = 1.242f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 15.693f, y1 = 12.917f)
            arcTo(horizontalEllipseRadius = 1.338f, verticalEllipseRadius = 1.338f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 14.258f, y1 = 12.384f)
            arcTo(horizontalEllipseRadius = 1.23f, verticalEllipseRadius = 1.23f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 13.915f, y1 = 12.534f)
            lineTo(11.782f, 13.894f)
            arcTo(horizontalEllipseRadius = 4.078f, verticalEllipseRadius = 4.078f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 10.647f, y1 = 14.393f)
            arcTo(horizontalEllipseRadius = 4.44f, verticalEllipseRadius = 4.44f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 5.882f, y1 = 12.627f)
            arcTo(horizontalEllipseRadius = 4.108f, verticalEllipseRadius = 4.108f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 5.18f, y1 = 9.519f)
            arcTo(horizontalEllipseRadius = 3.855f, verticalEllipseRadius = 3.855f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 6.922f, y1 = 6.937f)
            lineTo(12.511f, 3.374f)
            arcTo(horizontalEllipseRadius = 4.072f, verticalEllipseRadius = 4.072f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 13.646f, y1 = 2.875f)
            arcTo(horizontalEllipseRadius = 4.44f, verticalEllipseRadius = 4.44f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 18.411f, y1 = 4.642f)
            arcTo(horizontalEllipseRadius = 4.109f, verticalEllipseRadius = 4.109f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 19.114f, y1 = 7.749f)
            arcTo(horizontalEllipseRadius = 3.943f, verticalEllipseRadius = 3.943f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 18.98f, y1 = 8.271f)
            lineTo(18.875f, 8.592f)
            lineTo(18.589f, 8.382f)
            arcTo(horizontalEllipseRadius = 7.204f, verticalEllipseRadius = 7.204f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 16.402f, y1 = 7.289f)
            lineTo(16.194f, 7.226f)
            lineTo(16.214f, 7.019f)
            arcTo(horizontalEllipseRadius = 1.255f, verticalEllipseRadius = 1.255f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 15.988f, y1 = 6.188f)
            arcTo(horizontalEllipseRadius = 1.337f, verticalEllipseRadius = 1.337f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 14.553f, y1 = 5.656f)
            arcTo(horizontalEllipseRadius = 1.231f, verticalEllipseRadius = 1.231f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 14.21f, y1 = 5.806f)
            lineTo(8.62f, 9.368f)
            arcTo(horizontalEllipseRadius = 1.162f, verticalEllipseRadius = 1.162f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 8.096f, y1 = 10.146f)
            arcTo(horizontalEllipseRadius = 1.24f, verticalEllipseRadius = 1.24f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 8.307f, y1 = 11.083f)
            arcTo(horizontalEllipseRadius = 1.338f, verticalEllipseRadius = 1.338f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 9.742f, y1 = 11.616f)
            arcTo(horizontalEllipseRadius = 1.235f, verticalEllipseRadius = 1.235f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 10.086f, y1 = 11.465f)
            lineTo(12.218f, 10.105f)
            arcTo(horizontalEllipseRadius = 4.067f, verticalEllipseRadius = 4.067f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 13.353f, y1 = 9.607f)
            arcTo(horizontalEllipseRadius = 4.44f, verticalEllipseRadius = 4.44f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 18.118f, y1 = 11.373f)
            arcTo(horizontalEllipseRadius = 4.108f, verticalEllipseRadius = 4.108f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 18.82f, y1 = 14.481f)
            arcTo(horizontalEllipseRadius = 3.857f, verticalEllipseRadius = 3.857f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 17.078f, y1 = 17.064f)
            lineTo(11.489f, 20.626f)
            arcTo(horizontalEllipseRadius = 4.072f, verticalEllipseRadius = 4.072f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 10.354f, y1 = 21.125f)
            moveTo(20.712f, 3.175f)
            curveTo(18.484f, -0.015f, 14.082f, -0.96f, 10.9f, 1.068f)
            lineTo(5.31f, 4.63f)
            arcTo(horizontalEllipseRadius = 6.412f, verticalEllipseRadius = 6.412f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 2.414f, y1 = 8.925f)
            arcTo(horizontalEllipseRadius = 6.753f, verticalEllipseRadius = 6.753f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 3.08f, y1 = 13.261f)
            arcTo(horizontalEllipseRadius = 6.43f, verticalEllipseRadius = 6.43f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 2.12f, y1 = 15.657f)
            arcTo(horizontalEllipseRadius = 6.833f, verticalEllipseRadius = 6.833f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 3.288f, y1 = 20.824f)
            curveTo(5.517f, 24.014f, 9.918f, 24.959f, 13.1f, 22.932f)
            lineTo(18.69f, 19.37f)
            arcTo(horizontalEllipseRadius = 6.41f, verticalEllipseRadius = 6.41f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 21.586f, y1 = 15.075f)
            arcTo(horizontalEllipseRadius = 6.756f, verticalEllipseRadius = 6.756f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 20.921f, y1 = 10.739f)
            arcTo(horizontalEllipseRadius = 6.429f, verticalEllipseRadius = 6.429f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 21.879f, y1 = 8.343f)
            arcTo(horizontalEllipseRadius = 6.831f, verticalEllipseRadius = 6.831f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 20.712f, y1 = 3.175f)
            close()
            }
        }.build().also { _svelte = it }
    }
