// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.brands

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.BrandIcons

private var _tailwindcss: ImageVector? = null

/** Tailwind CSS brand mark (Simple Icons). */
public val BrandIcons.Tailwindcss: ImageVector
    get() {
        _tailwindcss?.let { return it }
        return ImageVector.Builder(
            name = "Brand.Tailwindcss",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(
                fill = SolidColor(Color(0xFF06B6D4)),
                stroke = null,
            ) {
            moveTo(12.001f, 4.8f)
            curveTo(8.801f, 4.8f, 6.801f, 6.4f, 6.001f, 9.6f)
            curveTo(7.201f, 8f, 8.601f, 7.4f, 10.201f, 7.8f)
            curveTo(11.114f, 8.028f, 11.766f, 8.69f, 12.489f, 9.424f)
            curveTo(13.666f, 10.618f, 15.027f, 12f, 18.001f, 12f)
            curveTo(21.201f, 12f, 23.201f, 10.4f, 24.001f, 7.2f)
            curveTo(22.801f, 8.8f, 21.401f, 9.4f, 19.801f, 9f)
            curveTo(18.888f, 8.772f, 18.236f, 8.11f, 17.513f, 7.376f)
            curveTo(16.337f, 6.182f, 14.976f, 4.8f, 12.001f, 4.8f)
            close()
            moveTo(6.001f, 12f)
            curveTo(2.801f, 12f, 0.801f, 13.6f, 0.001f, 16.8f)
            curveTo(1.201f, 15.2f, 2.601f, 14.6f, 4.201f, 15f)
            curveTo(5.114f, 15.228f, 5.766f, 15.89f, 6.489f, 16.624f)
            curveTo(7.666f, 17.818f, 9.027f, 19.2f, 12.001f, 19.2f)
            curveTo(15.201f, 19.2f, 17.201f, 17.6f, 18.001f, 14.4f)
            curveTo(16.801f, 16f, 15.401f, 16.6f, 13.801f, 16.2f)
            curveTo(12.888f, 15.972f, 12.236f, 15.31f, 11.513f, 14.576f)
            curveTo(10.337f, 13.382f, 8.976f, 12f, 6.001f, 12f)
            close()
            }
        }.build().also { _tailwindcss = it }
    }
