// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.brands

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.BrandIcons

private var _typeScript: ImageVector? = null

/** TypeScript brand mark (Simple Icons). */
public val BrandIcons.TypeScript: ImageVector
    get() {
        _typeScript?.let { return it }
        return ImageVector.Builder(
            name = "Brand.TypeScript",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(
                fill = SolidColor(Color(0xFF3178C6)),
                stroke = null,
            ) {
            moveTo(1.125f, 0f)
            curveTo(0.502f, 0f, 0f, 0.502f, 0f, 1.125f)
            verticalLineTo(22.875f)
            curveTo(0f, 23.498f, 0.502f, 24f, 1.125f, 24f)
            horizontalLineTo(22.875f)
            curveTo(23.498f, 24f, 24f, 23.498f, 24f, 22.875f)
            verticalLineTo(1.125f)
            curveTo(24f, 0.502f, 23.498f, 0f, 22.875f, 0f)
            close()
            moveTo(18.488f, 9.75f)
            curveTo(19.1f, 9.75f, 19.642f, 9.787f, 20.115f, 9.861f)
            arcTo(horizontalEllipseRadius = 6.38f, verticalEllipseRadius = 6.38f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 21.421f, y1 = 10.201f)
            verticalLineTo(12.659f)
            arcTo(horizontalEllipseRadius = 3.95f, verticalEllipseRadius = 3.95f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 20.778f, y1 = 12.298f)
            arcTo(horizontalEllipseRadius = 5.093f, verticalEllipseRadius = 5.093f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 20.061f, y1 = 12.038f)
            arcTo(horizontalEllipseRadius = 5.453f, verticalEllipseRadius = 5.453f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 18.635f, y1 = 11.838f)
            curveTo(18.335f, 11.838f, 18.062f, 11.866f, 17.816f, 11.924f)
            arcTo(horizontalEllipseRadius = 2.1f, verticalEllipseRadius = 2.1f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 17.193f, y1 = 12.166f)
            curveTo(17.023f, 12.27f, 16.893f, 12.395f, 16.8f, 12.54f)
            arcTo(horizontalEllipseRadius = 0.888f, verticalEllipseRadius = 0.888f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 16.66f, y1 = 13.03f)
            curveTo(16.66f, 13.226f, 16.713f, 13.403f, 16.816f, 13.559f)
            curveTo(16.92f, 13.715f, 17.068f, 13.863f, 17.259f, 14.003f)
            curveTo(17.45f, 14.143f, 17.682f, 14.279f, 17.955f, 14.413f)
            curveTo(18.228f, 14.548f, 18.537f, 14.687f, 18.881f, 14.829f)
            curveTo(19.351f, 15.026f, 19.773f, 15.236f, 20.147f, 15.457f)
            curveTo(20.521f, 15.679f, 20.842f, 15.93f, 21.11f, 16.21f)
            curveTo(21.378f, 16.489f, 21.582f, 16.808f, 21.724f, 17.167f)
            curveTo(21.866f, 17.526f, 21.938f, 17.943f, 21.938f, 18.42f)
            curveTo(21.938f, 19.077f, 21.813f, 19.63f, 21.565f, 20.076f)
            arcTo(horizontalEllipseRadius = 3.033f, verticalEllipseRadius = 3.033f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 20.553f, y1 = 21.161f)
            arcTo(horizontalEllipseRadius = 4.38f, verticalEllipseRadius = 4.38f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 19.066f, y1 = 21.757f)
            curveTo(18.5f, 21.877f, 17.903f, 21.937f, 17.276f, 21.937f)
            arcTo(horizontalEllipseRadius = 9.916f, verticalEllipseRadius = 9.916f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 15.436f, y1 = 21.773f)
            arcTo(horizontalEllipseRadius = 5.544f, verticalEllipseRadius = 5.544f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 13.924f, y1 = 21.28f)
            verticalLineTo(18.65f)
            arcTo(horizontalEllipseRadius = 5.033f, verticalEllipseRadius = 5.033f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 17.161f, y1 = 19.85f)
            curveTo(17.494f, 19.85f, 17.785f, 19.82f, 18.033f, 19.76f)
            curveTo(18.282f, 19.7f, 18.489f, 19.616f, 18.656f, 19.51f)
            curveTo(18.822f, 19.402f, 18.946f, 19.276f, 19.029f, 19.13f)
            arcTo(horizontalEllipseRadius = 1.023f, verticalEllipseRadius = 1.023f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 18.955f, y1 = 18.041f)
            arcTo(horizontalEllipseRadius = 2.12f, verticalEllipseRadius = 2.12f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 18.418f, y1 = 17.541f)
            arcTo(horizontalEllipseRadius = 5.597f, verticalEllipseRadius = 5.597f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 17.611f, y1 = 17.097f)
            arcTo(horizontalEllipseRadius = 27.72f, verticalEllipseRadius = 27.72f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 16.604f, y1 = 16.661f)
            curveTo(15.686f, 16.278f, 15.002f, 15.809f, 14.551f, 15.256f)
            curveTo(14.101f, 14.703f, 13.875f, 14.034f, 13.875f, 13.251f)
            curveTo(13.875f, 12.637f, 13.998f, 12.11f, 14.244f, 11.669f)
            curveTo(14.49f, 11.228f, 14.824f, 10.865f, 15.248f, 10.58f)
            arcTo(horizontalEllipseRadius = 4.494f, verticalEllipseRadius = 4.494f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 16.718f, y1 = 9.951f)
            arcTo(horizontalEllipseRadius = 7.536f, verticalEllipseRadius = 7.536f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 18.488f, y1 = 9.75f)
            close()
            moveTo(3.375f, 9.938f)
            horizontalLineTo(12.938f)
            verticalLineTo(12.104f)
            horizontalLineTo(9.506f)
            verticalLineTo(21.75f)
            horizontalLineTo(6.789f)
            verticalLineTo(12.104f)
            horizontalLineTo(3.375f)
            close()
            }
        }.build().also { _typeScript = it }
    }
