// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.brands

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.BrandIcons

private var _vite: ImageVector? = null

/** Vite brand mark (Simple Icons). */
public val BrandIcons.Vite: ImageVector
    get() {
        _vite?.let { return it }
        return ImageVector.Builder(
            name = "Brand.Vite",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(
                fill = SolidColor(Color(0xFF646CFF)),
                stroke = null,
            ) {
            moveTo(8.286f, 10.578f)
            lineTo(8.798f, 1.921f)
            arcTo(horizontalEllipseRadius = 0.306f, verticalEllipseRadius = 0.306f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 9.045f, y1 = 1.639f)
            lineTo(17.377f, 0.006f)
            arcTo(horizontalEllipseRadius = 0.306f, verticalEllipseRadius = 0.306f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 17.73f, y1 = 0.391f)
            lineTo(16.172f, 5.794f)
            arcTo(horizontalEllipseRadius = 0.306f, verticalEllipseRadius = 0.306f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 16.524f, y1 = 6.179f)
            lineTo(18.912f, 5.719f)
            arcTo(horizontalEllipseRadius = 0.306f, verticalEllipseRadius = 0.306f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 19.244f, y1 = 6.157f)
            lineTo(12.454f, 19.707f)
            lineTo(12.331f, 19.897f)
            arcTo(horizontalEllipseRadius = 0.294f, verticalEllipseRadius = 0.294f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 12.079f, y1 = 20.037f)
            curveTo(11.902f, 20.037f, 11.729f, 19.885f, 11.774f, 19.668f)
            lineTo(12.869f, 14.367f)
            arcTo(horizontalEllipseRadius = 0.306f, verticalEllipseRadius = 0.306f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 12.481f, y1 = 14.012f)
            lineTo(11.048f, 14.447f)
            arcTo(horizontalEllipseRadius = 0.306f, verticalEllipseRadius = 0.306f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 10.659f, y1 = 14.093f)
            lineTo(11.349f, 10.718f)
            arcTo(horizontalEllipseRadius = 0.306f, verticalEllipseRadius = 0.306f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 10.979f, y1 = 10.358f)
            lineTo(8.659f, 10.894f)
            arcTo(horizontalEllipseRadius = 0.306f, verticalEllipseRadius = 0.306f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 8.285f, y1 = 10.578f)
            close()
            moveTo(23.262f, 2.652f)
            lineTo(17.284f, 3.74f)
            lineTo(16.74f, 5.627f)
            lineTo(18.817f, 5.227f)
            arcTo(horizontalEllipseRadius = 0.8f, verticalEllipseRadius = 0.8f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 19.657f, y1 = 5.596f)
            arcTo(horizontalEllipseRadius = 0.8f, verticalEllipseRadius = 0.8f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 19.691f, y1 = 6.379f)
            lineTo(12.9f, 19.93f)
            lineTo(12.887f, 19.955f)
            lineTo(12.872f, 19.978f)
            lineTo(12.75f, 20.168f)
            arcTo(horizontalEllipseRadius = 0.801f, verticalEllipseRadius = 0.801f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 12.078f, y1 = 20.538f)
            arcTo(horizontalEllipseRadius = 0.826f, verticalEllipseRadius = 0.826f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 11.444f, y1 = 20.236f)
            arcTo(horizontalEllipseRadius = 0.8f, verticalEllipseRadius = 0.8f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 11.284f, y1 = 19.566f)
            lineTo(12.313f, 14.585f)
            lineTo(11.193f, 14.925f)
            arcTo(horizontalEllipseRadius = 0.81f, verticalEllipseRadius = 0.81f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 10.333f, y1 = 14.663f)
            arcTo(horizontalEllipseRadius = 0.802f, verticalEllipseRadius = 0.802f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 10.168f, y1 = 13.993f)
            lineTo(10.798f, 10.913f)
            lineTo(8.771f, 11.381f)
            arcTo(horizontalEllipseRadius = 0.808f, verticalEllipseRadius = 0.808f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 8.003f, y1 = 11.148f)
            arcTo(horizontalEllipseRadius = 0.81f, verticalEllipseRadius = 0.81f, theta = 0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 7.786f, y1 = 10.548f)
            lineTo(8.175f, 3.978f)
            lineTo(0.735f, 2.648f)
            arcTo(horizontalEllipseRadius = 0.612f, verticalEllipseRadius = 0.612f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 0.095f, y1 = 3.554f)
            lineTo(11.58f, 23.691f)
            arcTo(horizontalEllipseRadius = 0.612f, verticalEllipseRadius = 0.612f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 12.646f, y1 = 23.687f)
            lineTo(23.906f, 3.552f)
            arcTo(horizontalEllipseRadius = 0.612f, verticalEllipseRadius = 0.612f, theta = 0f, isMoreThanHalf = false, isPositiveArc = false, x1 = 23.262f, y1 = 2.652f)
            close()
            }
        }.build().also { _vite = it }
    }
