// Generated by scripts/generate_wash_compose_icons.py. Do not edit by hand.
package com.mariesta.menzies.washui.icons.brands

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.mariesta.menzies.washui.icons.BrandIcons

private var _vue: ImageVector? = null

/** Vue.js brand mark (Simple Icons). */
public val BrandIcons.Vue: ImageVector
    get() {
        _vue?.let { return it }
        return ImageVector.Builder(
            name = "Brand.Vue",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(
                fill = SolidColor(Color(0xFF4FC08D)),
                stroke = null,
            ) {
            moveTo(24f, 1.61f)
            horizontalLineTo(14.06f)
            lineTo(12f, 5.16f)
            lineTo(9.94f, 1.61f)
            horizontalLineTo(0f)
            lineTo(12f, 22.39f)
            close()
            moveTo(12f, 14.08f)
            lineTo(5.16f, 2.23f)
            horizontalLineTo(9.59f)
            lineTo(12f, 6.41f)
            lineTo(14.41f, 2.23f)
            horizontalLineTo(18.84f)
            close()
            }
        }.build().also { _vue = it }
    }
